wolfSSL/wolfssljni

native/com_wolfssl_WolfSSLSession.c, src/test/com/wolfssl/WolfSSLSessionTest.java
This PR adds better cleanup, by setting the internal pointer to NULL that stores the WolfSSLSession reference.
=> reset internal WolfSSLSession pointer to NULL when object is freed

examples/Client.java, examples/Server.java, examples/certs/ca-cert.pem, examples/certs/client-cert.pem, examples/certs/crl/cliCrl.pem, examples/certs/crl/crl.pem, examples/certs/crl/crl.revoked, examples/certs/crl/eccCliCRL.pem, examples/certs/crl/eccSrvCRL.pem, examples/certs/server-cert.pem, examples/certs/server-ecc.pem
This PR:
- Updates the certs to match ones in the wolfSSL master repo
- Fixes I/O callback usage in the example client and server
=> Update certs, fix I/O callback usage in examples

src/java/com/wolfssl/WolfSSLCustomUser.java, src/java/com/wolfssl/provider/jsse/WolfSSLContext.java
Add WolfSSLCustomUser.GetCtxAttributes
=> Custom CB for CreateContext

native/com_wolfssl_WolfSSLCertManager.c, native/com_wolfssl_WolfSSLCertificate.c, native/com_wolfssl_WolfSSLContext.c, native/com_wolfssl_WolfSSLSession.c, native/com_wolfssl_WolfSSLX509StoreCtx.c
=> stdint.h for uintptr_t

src/java/com/wolfssl/provider/jsse/WolfSSLAuthStore.java, src/java/com/wolfssl/provider/jsse/WolfSSLContext.java, src/java/com/wolfssl/provider/jsse/WolfSSLEngineHelper.java, src/java/com/wolfssl/provider/jsse/WolfSSLKeyManager.java, src/java/com/wolfssl/provider/jsse/WolfSSLKeyX509.java, src/java/com/wolfssl/provider/jsse/WolfSSLServerSocket.java, src/java/com/wolfssl/provider/jsse/WolfSSLServerSocketFactory.java, src/java/com/wolfssl/provider/jsse/WolfSSLSocket.java, src/java/com/wolfssl/provider/jsse/WolfSSLSocketFactory.java, src/java/com/wolfssl/provider/jsse/WolfSSLTrustManager.java, src/java/com/wolfssl/provider/jsse/WolfSSLTrustX509.java, src/java/com/wolfssl/provider/jsse/WolfSSLX509.java, src/java/com/wolfssl/provider/jsse/WolfSSLX509X.java
This PR adds additional debug log messages to wolfJSSE.  This will make it easier to debug remote/customer/user issues.
=> Add more debug logs to JSSE

src/java/com/wolfssl/provider/jsse/WolfSSLContext.java, src/java/com/wolfssl/provider/jsse/WolfSSLEngine.java, src/java/com/wolfssl/provider/jsse/WolfSSLEngineHelper.java, src/java/com/wolfssl/provider/jsse/WolfSSLImplementSSLSession.java, src/java/com/wolfssl/provider/jsse/WolfSSLParameters.java, src/java/com/wolfssl/provider/jsse/WolfSSLServerSocket.java, src/java/com/wolfssl/provider/jsse/WolfSSLSocket.java, src/java/com/wolfssl/provider/jsse/WolfSSLSocketFactory.java, src/java/com/wolfssl/provider/jsse/WolfSSLTrustManager.java
- fix for missing throw exception
- infer null deref. warnings
- infer THREAD_SAFETY_VIOLATION warnings
=> add exception for null init and static analysis fixes

src/java/com/wolfssl/provider/jsse/WolfSSLAuthStore.java, src/java/com/wolfssl/provider/jsse/WolfSSLContext.java, src/java/com/wolfssl/provider/jsse/WolfSSLEngineHelper.java, src/java/com/wolfssl/provider/jsse/WolfSSLImplementSSLSession.java, src/java/com/wolfssl/provider/jsse/WolfSSLSessionContext.java, src/test/com/wolfssl/provider/jsse/test/WolfSSLContextTest.java, src/test/com/wolfssl/provider/jsse/test/WolfSSLEngineTest.java, src/test/com/wolfssl/provider/jsse/test/WolfSSLJSSETestSuite.java, src/test/com/wolfssl/provider/jsse/test/WolfSSLSessionContextTest.java, src/test/com/wolfssl/provider/jsse/test/WolfSSLSessionTest.java, src/test/com/wolfssl/provider/jsse/test/WolfSSLTestFactory.java
TLS 1.3 Session ID support left TODO and additional testing
=> initial refactor of SSLSessionContext implementation

src/java/com/wolfssl/provider/jsse/WolfSSLEngine.java, src/test/com/wolfssl/provider/jsse/test/WolfSSLTestFactory.java
This PR fixes handling of shutdown / close_notify alerts in the WolfSSLEngine implementation.
Should fix failing nightly Jenkins test.
=> fixes for SSLEngine handling of shutdown / close_notify 

examples/provider/ClientJSSE.java
This PR adds an option to the example JSSE client (ClientJSSE.java) that does one session resumption.
=> add option to do one session resumption to ClientJSSE example

src/java/com/wolfssl/provider/jsse/WolfSSLTrustManager.java
This PR adds support to WolfSSLTrustManager for loading system CA certificates from the default location in Java 9+.
Java 9+ includes `cacerts` at `$JAVA_HOME/lib/security/cacerts` instead of `$JAVA_HOME/jre/lib/security/cacerts`.
=> WolfSSLTrustManager: add support for loading default cacerts in Java 9+

IDE/Android/README.md, README.md
This PR simply updates the 1.9.0 release date in the README.md.  Also fixes IDE/Android/README.md gradle version.
=> Update release date for 1.9.0 in README

src/java/com/wolfssl/provider/jsse/WolfSSLTrustX509.java
This PR adds additional comments and a few more error checks to WolfSSLTrustX509.checkServerTrusted() implementations.
=> More error checks in WolfSSLTrustX509.checkServerTrusted()

.gitignore, scripts/infer.sh, src/java/com/wolfssl/WolfSSL.java, src/java/com/wolfssl/WolfSSLCertManager.java, src/java/com/wolfssl/WolfSSLCertificate.java, src/java/com/wolfssl/WolfSSLContext.java, src/java/com/wolfssl/WolfSSLSession.java, src/java/com/wolfssl/provider/jsse/WolfSSLEngine.java, src/java/com/wolfssl/provider/jsse/WolfSSLEngineHelper.java, src/java/com/wolfssl/provider/jsse/WolfSSLImplementSSLSession.java, src/java/com/wolfssl/provider/jsse/WolfSSLSocket.java
This PR adds a simple bash script to run Facebook Infer over Java classes in this project:
```
$ cd wolfssljni
$ ./scripts/infer.sh
```
This also fixes reports that showed up on the current codebase.
=> Facebook Infer script and fixes

IDE/Android/app/src/main/java/com/example/wolfssl/MainActivity.java, examples/Server.java, src/java/com/wolfssl/WolfSSL.java, src/java/com/wolfssl/WolfSSLCertificate.java, src/java/com/wolfssl/WolfSSLContext.java, src/java/com/wolfssl/WolfSSLPskClientCallback.java, src/java/com/wolfssl/WolfSSLPskServerCallback.java, src/java/com/wolfssl/WolfSSLX509StoreCtx.java, src/java/com/wolfssl/provider/jsse/WolfSSLAuthStore.java, src/java/com/wolfssl/provider/jsse/WolfSSLContext.java, src/java/com/wolfssl/provider/jsse/WolfSSLCustomUser.java, src/java/com/wolfssl/provider/jsse/WolfSSLDebug.java, src/java/com/wolfssl/provider/jsse/WolfSSLEngine.java, src/java/com/wolfssl/provider/jsse/WolfSSLEngineHelper.java, src/java/com/wolfssl/provider/jsse/WolfSSLImplementSSLSession.java, src/java/com/wolfssl/provider/jsse/WolfSSLInternalVerifyCb.java, src/java/com/wolfssl/provider/jsse/WolfSSLKeyManager.java, src/java/com/wolfssl/provider/jsse/WolfSSLKeyX509.java, src/java/com/wolfssl/provider/jsse/WolfSSLParametersHelper.java, src/java/com/wolfssl/provider/jsse/WolfSSLSocket.java, src/java/com/wolfssl/provider/jsse/WolfSSLSocketFactory.java, src/java/com/wolfssl/provider/jsse/WolfSSLTrustManager.java, src/java/com/wolfssl/provider/jsse/WolfSSLTrustX509.java, src/java/com/wolfssl/provider/jsse/WolfSSLX509.java, src/java/com/wolfssl/provider/jsse/WolfSSLX509X.java, src/test/com/wolfssl/provider/jsse/test/WolfSSLContextTest.java
This PR includes initial fixes and changes based on scan with [SonarQube](https://www.sonarsource.com/products/sonarqube/) static analyzer.
Not all these were bugs, but several code improvements.
=> Initial fixes from SonarQube

examples/Server.java
Added try-catch statement to catch any errors produced by "serverSocket.close()" to fix compilation issues.
=> Added try-catch to fix compilation errors

src/java/com/wolfssl/WolfSSLCertManager.java, src/java/com/wolfssl/WolfSSLContext.java, src/java/com/wolfssl/WolfSSLSession.java, src/java/com/wolfssl/WolfSSLX509StoreCtx.java, src/java/com/wolfssl/provider/jsse/WolfSSLImplementSSLSession.java
This PR adds missing synchronization locks around native structure pointer use and active object state for the following JNI classes:
- WolfSSLCertManager (WOLFSSL_CERT_MANAGER)
- WolfSSLContext (WOLFSSL_CTX)
- WolfSSLSession (WOLFSSL)
- WolfSSLX509StoreCtx (WOLFSSL_X509_STORE_CTX)
- WolfSSLImplementSSLSession (WOLFSSL_SESSION)
=> Add synchronization locks around native pointer use and active state

examples/provider/ClientJSSE.java
This PR makes changes to the example JSSE client (`examples/provider/ClientJSSE.java`), including:
- Fixes the `-d` option to disable peer verification. The example had been calling `sock.setNeedClientAuth(false);`, but that is only applicable on the server side.  This adds and registers a custom `X509TrustManager` which will verify all peers when the `-d` option is used.
- Adds a `-g` option to send an HTTP GET message to the peer. Mirrors behavior of wolfSSL proper example client.
=> Fix JSSE example client -d option, add -g for HTTP GET

native/com_wolfssl_WolfSSLContext.c, native/com_wolfssl_wolfcrypt_EccKey.c
found when testing https://github.com/wolfSSL/wolfssljni/pull/159 against wolfSSL master branch
=> fixes for heap hint used

src/java/com/wolfssl/provider/jsse/WolfSSLKeyX509.java, src/test/com/wolfssl/provider/jsse/test/WolfSSLKeyX509Test.java
This PR expands `WolfSSLKeyX509` to implement the `X509ExtendedKeyManager` class. This adds implementations of the following two methods:
- `chooseEngineClientAlias()`
- `chooseEngineServerAlias()`
ZD 17248
=> JSSE: add implementation of X509ExtendedKeyManager

src/java/com/wolfssl/provider/jsse/WolfSSLContext.java, src/java/com/wolfssl/provider/jsse/WolfSSLEngine.java, src/java/com/wolfssl/provider/jsse/WolfSSLSocket.java, src/java/com/wolfssl/provider/jsse/WolfSSLTrustX509.java
Fix Sun JSSE Test issues.
Tests fixed:
- SSLEngine/ArgCheck.java
- SSLEngineImpl/CloseEngineException.java
- SSLSocket/InputStreamClosure.java
- SSLSocket/OutputStreamClosure.java
- SSLSocketImpl/CloseSocketException.java
- X509TrustManagerImpl/CheckNullEntity.java
Associated PR: https://github.com/wolfSSL/testing/pull/571
=> Fix sun jsse test issues.

native/com_wolfssl_WolfSSLSession.c
This PR modifies JNI-level behavior when calling native `select()` on Unix/Linux platforms.  If `select()` was interrupted, returns `-1`, and `errno == EINTR`, loop and try again.
ZD 17385
=> JNI: call select() again on error with EINTR

.github/workflows/main.yml, .github/workflows/maven.yml
This PR adds a GitHub Action that runs on all PRs and tests the Maven (pom.xml) build on both Linux and Mac OS. This will make sure our pom.xml build doesn't get broken along the way.
Result of runs of this action on this PR are:
Linux: https://github.com/wolfSSL/wolfssljni/actions/runs/11787311760/job/32832348416?pr=232
Mac: https://github.com/wolfSSL/wolfssljni/actions/runs/11787311760/job/32832348230?pr=232
=> Add GitHub Action PRB to test Maven builds (pom.xml)

native/com_wolfssl_WolfSSLSession.c, src/test/com/wolfssl/test/WolfSSLSessionTest.java
This PR:
- Adds more return code and error condition checks inside the native JNI `WolfSSLSession.read(ByteBuffer, ...)` function.
- Adjusts JNI-layer test for `WolfSSLSession.test_WolfSSLSession_ioBuffers()` to add checks for `SSL_ERROR_WANT_READ` and `SSL_ERROR_WANT_WRITE` when calling `read()/write()`.
=> Add more checks to JNI WolfSSLSession.read(ByteBuffer)

.gitignore, CLAUDE.md
This PR adds `CLAUDE.md`, as recommended by Anthropic Claude Code [Best Practices](https://www.anthropic.com/engineering/claude-code-best-practices) guide.
=> Add CLAUDE.md for consumption by Claude Code

src/java/com/wolfssl/WolfSSLNativeLoggingCallback.java
Changes logging callback for wolfSSL debug messages to stderr.
=> change wolfSSL logging cb to stderr

src/java/com/wolfssl/provider/jsse/WolfSSLUtil.java
WolfJSSE does not support DTLSv1 and DTLSv1.2. Add these to disabled algorithms and modify when these algorithms are available.
=> always disable DTLSv1 and DTLSv1.2

.github/workflows/address-sanitizer.yml, .github/workflows/infer.yml, .github/workflows/linux-common.yml, .github/workflows/main.yml
This PR adds a new GitHub Action to that runs `ant test` with native wolfSSL and JNI sources compiled with `-fsanitize=address`.
This has been negative tested to verify that it will catch issues. Example failing run:
https://github.com/cconlon/wolfssljni/actions/runs/15590494573/job/43908051903
=> Testing: add GitHub Action for -fsanitize=address
