- examples/Client.java
- examples/Server.java
- java.sh
- native/com_wolfssl_WolfSSL.c
- native/com_wolfssl_WolfSSL.h
- native/com_wolfssl_WolfSSLContext.c
- native/com_wolfssl_WolfSSLSession.c
- src/java/com/wolfssl/WolfSSL.java
- src/test/com/wolfssl/WolfSSLContextTest.java
- src/test/com/wolfssl/WolfSSLSessionTest.java
This pull request removes dependencies on wolfSSL native features that were requirements before (including WOLFSSL_DTLS, PERSIST_SESSION_CACHE, KEEP_PEER_CERT, SESSION_CERTS, HAVE_CRL, HAVE_OCSP, ATOMIC_USER, HAVE_PK_CALLBACKS)
It also adds methods to check if features are enabled in the native wolfSSL library.  These are used by the example client/server.
> Remove native wolfSSL feature dependencies

- src/java/com/wolfssl/WolfSSLContext.java
- src/java/com/wolfssl/WolfSSLSession.java
The try/catch/finalize block is not necessary in these two methods, as the finalize() method already throws "Throwable".
> remove try/catch block from finalize methods

- src/java/com/wolfssl/WolfSSL.java
wolfSSL JNI previously had two methods for the Java application to load the native JNI library:
```
public static void loadLibrary();
public static void loadLibrary(String libName);
```
These both loaded a shared library from the system's library search path.  Theoretically, an attacker could attempt to load malicious code by injecting a library of the same name earlier in the library search path.
This adds a new method for loading the native JNI library that accepts an absolute path name to a library file, thus eliminating possibility mentioned above:
`public static void loadLibraryAbsolute(String libPath)`
> add method to load JNI library from specific path, loadLibraryAbsolute()

- examples/Client.java
- examples/MyDecryptVerifyCallback.java
- examples/MyMacEncryptCallback.java
- examples/Server.java
- native/com_wolfssl_WolfSSL.c
- native/com_wolfssl_WolfSSL.h
- src/java/com/wolfssl/WolfSSL.java
This PR:
- Fixes the registration of atomic user callbacks in the example client and server
- Switches WolfSSL.java to get the BulkCipherAlgorithm enum values dynamically (since the native code enums can change due to ifdef configuration)
- Allows additional non-SHA1 Hmac types to be used in the atomic user callback examples.  They previously only supported HmacSHA1.
> Fix Atomic User callback registration in examples

- README
- examples/provider/ProviderTest.java
This adds a simple example app that shows information about installed Security Providers. It can be helpful for testing system installation of wolfJSSE to make sure it is installed correctly.
> add example app to see installed Security Providers

- src/java/com/wolfssl/provider/jsse/WolfSSLContext.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLTrustX509Test.java
This fixes a few ant test failures that were showing up with OpenJDK 7, including:
- Difference in KeyStore certificate ordering after importing from .jks files
- Workaround for bug in JDK 7 (1.7.0_201) when using EC keys with PrivateKey class
> Fixes to resolve ant test failures on OpenJDK 7

- README
- build.xml
Separate build of tests and examples from main jar. This helps by not stopping the build of the main code source if JUNIT is not setup in the exact way that build.xml expects on the system.
Build options
- ant build
- ant examples
- ant test
> add build of tests and examples seperate from build of jar

- src/java/com/wolfssl/provider/jsse/WolfSSLContext.java
- src/java/com/wolfssl/provider/jsse/WolfSSLProvider.java
- src/java/com/wolfssl/provider/jsse/WolfSSLSocketFactory.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLContextTest.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLSocketFactoryTest.java
This PR includes JSSE additions:
1.  Adds support for JSSE use cases that call SSLSocketFactory.getDefault()
2.  Adds support for SSLContext.getDefaultSSLParameters()
3.  Adds support for SSLContext.getSupportedSSLParameters()
4.  Adds better native library init in WolfSSLProvider
> SSLSocketFactory.getDefault() support, WolfSSLContext getters

- src/test/com/wolfssl/provider/jsse/test/WolfSSLContextTest.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLEngineTest.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLKeyX509Test.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLServerSocketFactoryTest.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLServerSocketTest.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLSessionTest.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLSocketFactoryTest.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLSocketTest.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLTrustX509Test.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLX509Test.java
This PR changes how wolfJSSE is registered as a Security Provider in our junit tests.  Previously we were using "Security.addProvider()", but on some systems this does not register wolfJSSE as the highest priority Provider.  Using "Security.insertProviderAt()" instead allows us to explicitly register wolfJSSE as the first priority provider.
> register wolfJSSE as first Security provider in unit tests

- src/java/com/wolfssl/provider/jsse/WolfSSLTrustManager.java
On Android, when loading trusted system certificates, we should free the WolfSSLCertificate explicitly after we are finished with it.
> free WolfSSLCertificate in WolfSSLTrustManager when done with it

- src/java/com/wolfssl/WolfSSLCertManager.java
- src/java/com/wolfssl/WolfSSLCertificate.java
This PR adds finalize() methods to the WolfSSLCertManager and WolfSSLCertificate classes, to protect against any cases where users might not call free() explicitly.
> add finalize() methods for WolfSSLCertManager, WolfSSLCertificate

- src/java/com/wolfssl/provider/jsse/WolfSSLImplementSSLSession.java
Prevent a null pointer exception if certs is null, before calling certs.length.
> check X509Certificate[] for null in getLocalPrincipal()

- src/java/com/wolfssl/provider/jsse/WolfSSLContext.java
In case the underlying WolfSSLContext has already been freed, have cleanup() catch the IllegalStateException to prevent users from seeing it pop up.
> catch IllegalStateException in WolfSSLContext cleanup()

- src/java/com/wolfssl/provider/jsse/WolfSSLContext.java
- src/java/com/wolfssl/provider/jsse/WolfSSLSocketFactory.java
This PR:
1) Fixes how WolfSSLSocketFactory stores the DEFAULT_Context reference.  Previously the reference lost scope after the constructor exited.
2) Removes unnecessary finalize() methods in WolfSSLContext inner classes.  The outer WolfSSLContext finalize() will always be called when an inner class goes out of scope and is garbage collected.
3)  Changes com.wolfssl.provider.jsse.WolfSSLContext finalizer so that it does not free the underlying com.wolfssl.WolfSSLContext.  Some objects/classes may still hold references to the underlying WolfSSLContext which they need.  The underlying WolfSSLContext will be freed by its own finalize() method when needed.
> WolfSSLSocketFactory, WolfSSLContext fixes

- src/java/com/wolfssl/provider/jsse/WolfSSLContext.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngineHelper.java
- src/java/com/wolfssl/provider/jsse/WolfSSLServerSocket.java
- callback filter is effective after creating context in createCtx
- getAllProtocols to get built in protocols
- getSupportedProtocols to get protocols after the filter
> fix on TLS version filter

- README
- src/java/com/wolfssl/provider/jsse/WolfSSLProvider.java
Adds support for a new system parameter called "wolfssl.debug".  When set to true at runtime, this will enable native wolfSSL debug logging with wolfJSSE.
For example, when running a Java app that uses wolfJSSE, and native wolfSSL has been compiled with "--enable-debug":
```
$ java -Dwolfssl.debug=true TestApp
```
> add wolfssl.debug parameter for native debug with JSSE

- README
- native/com_wolfssl_WolfSSLSession.c
This PR adds checks for NO_DH around DH-related functionality in native/com_wolfssl_WolfSSLSession.c.
> fix build with DH disabled

- src/java/com/wolfssl/provider/jsse/WolfSSLKeyX509.java
This PR makes 2 changes to WolfSSLKeyX509:
1.  Removes an un-necessary UnsupportedOperationException from chooseClientAlias() when the Socket argument is null.  wolfJSSE does not require the Socket argument to match aliases, so we should not stop execution with an exception if the user does not pass one in.
2.  Normalizes the spacing after commas in the issuer name comparison of getAliases().  In some JDK implementations, the Principal[] issuer array passed in has no spaces after commas in the issuer name.
> WolfSSLKeyX509 Adjustments

- native/com_wolfssl_WolfSSLCertificate.c
- native/com_wolfssl_WolfSSLSession.c
- native/com_wolfssl_WolfSSLSession.h
- src/java/com/wolfssl/WolfSSLSession.java
- src/java/com/wolfssl/provider/jsse/WolfSSLContext.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngineHelper.java
- src/java/com/wolfssl/provider/jsse/WolfSSLSocket.java
- src/java/com/wolfssl/provider/jsse/WolfSSLSocketFactory.java
- src/java/com/wolfssl/provider/jsse/WolfSSLTrustX509.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLSocketTest.java
This PR contains four fixes:
- In WolfSSLInputStream/OutputStream, check if the connection has already been closed before trying to complete the handshake
- In WolfSSLEngineHelper.setLocalCiphers(), add length check to StringBuilder before modifying. Prevents StringIndexOutOfBoundsException.
- Add support for setSoTimeout() in WolfSSLSocket.  If called by an application, this timeout value will get used in select() calls made by socket SSL_read() and SSL_shutdown() operations.
- Adjust WolfSSLTrustX509.certManagerVerify() to verify and load intermediate chain certs before verifying peer.
- In WolfSSLSocket.close(), first check to see if close() has already been called before by checking if the underlying Socket has been closed.  If it has been closed, there is no reason to call …
> WolfSSLSocket, WolfSSLTrustX509 fixes

- src/java/com/wolfssl/provider/jsse/WolfSSLParameters.java
Fixes potential NullPointerException on "parameters.clone()" when input "protocols" would be null.  Also fixes similar issue with setApplicationProtocols() and null protocols.
> prevent NullPointerException in WolfSSLParameters.setProtocols()

- src/java/com/wolfssl/provider/jsse/WolfSSLSocket.java
This PR adds wrappers for Socket (java.net.Socket) methods which corrects behavior when inner Socket is used with WolfSSLSocket.
> Wrap Socket methods in WolfSSLSocket for correct use with inner Socket

- native/com_wolfssl_WolfSSL.c
- native/com_wolfssl_WolfSSL.h
- src/java/com/wolfssl/WolfSSL.java
- src/java/com/wolfssl/WolfSSLFIPSErrorCallback.java
- src/java/com/wolfssl/provider/jsse/WolfSSLProvider.java
This PR wraps native wolfCrypt_SetCb_fips() and wolfCrypt_GetCoreHash_fips(), so that wolfCrypt FIPS users can get/see the verifyCore hash needed to update in fips_test.c.
Two new methods are added to the WolfSSL class to be used for non-JSSE consumers:
- `public final static native int setFIPSCb(WolfSSLFIPSErrorCallback cb);`
- `public final static native String getWolfCryptFIPSCoreHash();`
For wolfJSSE users, WolfSSLProvider automatically registers an internal WolfSSLFIPSErrorCallback in WolfSSLProvider.java when the provider is initialized.  This will automatically set up the FIPS error callback for JSSE users, and they will see output from the callback show up in the debug log.
To see the debug output of wolfJSSE, the `wolfjsse.debug` system property needs to be set to `true` (ie: …
> Add wrappers to get FIPS verifyCore hash (FIPS error callback, or directly)

- src/java/com/wolfssl/provider/jsse/WolfSSLParameters.java
Fixes potential NullPointerException in getCipherSuites(), getProtocols(), and getApplicationProtocols() when clone() would have been called on a null object.
> prevent NullPointerException in WolfSSLParameters.getCipherSuites()

- src/java/com/wolfssl/provider/jsse/WolfSSLSocket.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLSocketFactoryTest.java
This PR corrects the behavior of WolfSSLSocket.getSoTimeout() when the WolfSSLSocket object has been created to use an inner socket.
This removes the use of the local variable "readTimeout" and instead directly uses the timeout value as received from Socket.getSoTimeout().
> Correct behavior of WolfSSLSocket.getSoTimeout()

- native/com_wolfssl_WolfSSL.c
- native/com_wolfssl_WolfSSLCertificate.c
- native/com_wolfssl_WolfSSLContext.c
- native/com_wolfssl_WolfSSLSession.c
- src/java/com/wolfssl/WolfSSL.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngineHelper.java
- src/java/com/wolfssl/provider/jsse/WolfSSLImplementSSLSession.java
- src/java/com/wolfssl/provider/jsse/WolfSSLInternalVerifyCb.java
- src/java/com/wolfssl/provider/jsse/WolfSSLKeyX509.java
- src/java/com/wolfssl/provider/jsse/WolfSSLProvider.java
- src/java/com/wolfssl/provider/jsse/WolfSSLSNIServerName.java
- src/java/com/wolfssl/provider/jsse/WolfSSLSocket.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLX509Test.java
Changes and fixes in this PR are related to memory use optimization and memory cleanup:
- Fixes a memory leak when users/applications used a custom X509TrustManager and wolfJSSE created a native global reference for WolfSSLInternalVerifyCb object (https://github.com/wolfSSL/wolfssljni/pull/69/commits/96f365a5e02f04222d1be4be7b01482b223a4ee2).
- Adds support for multiple simultaneous WOLFSSL sessions registering a custom X509TrustManager concurrently.  Previously the JNI native code maintained one global reference to a WolfSSLInternalVerifyCb object.  This meant that a single WolfSSLSession could have the callback registered.  This PR stores the global native WolfSSLInternalVerifyCb reference inside each native WOLFSSL session structure, thus making it possible for each WolfSSLSession to …
> Internal verify callback fixes and rework

- examples/provider/ProviderTest.java
- examples/provider/ProviderTest.sh
This PR cleans up the JSSE ProviderTest example. Previously it only printed out providers registered at the system level. It now prints that out first, then registers wolfJSSE at runtime, then prints provider info again.
Helpful for seeing what classes wolfJSSE registers without installing at system level.
> clean up JSSE ProviderTest example, register wolfJSSE

- native/com_wolfssl_WolfSSL.c
- native/com_wolfssl_wolfcrypt_EccKey.c
This PR uses the `uintptr_t` type when casting pointer values, instead of `intptr_t`.  We were using `uintptr_t` most places, except for a few in `com_wolfssl_WolfSSL.c` and `com_wolfssl_wolfcrypt_EccKey.c`.
> use uintptr_t instead of intptr_t in com_wolfssl_WolfSSL.c

- src/java/com/wolfssl/WolfSSL.java
- src/java/com/wolfssl/WolfSSLCertManager.java
- src/java/com/wolfssl/WolfSSLCertificate.java
- src/java/com/wolfssl/WolfSSLContext.java
- src/java/com/wolfssl/WolfSSLSession.java
This PR adds synchronization to class cleanup/free routines so that only one thread can enter the respective free() at a time.  Could prevent a scenario where multiple threads call native free() functions at the same time on the same pointer.
> synchronize class free() calls that access native cleanup functions

- src/java/com/wolfssl/provider/jsse/WolfSSLSocket.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLSocketTest.java
This PR modifies the SSLSocket.getSession() method to try and do the SSL/TLS handshake if it has not yet been completed.
This matches behavior of other JSSE providers.  It seems some applications call SSLSocket.getSession() and expect the handshake to be executed at that time.
> SSLSocket.getSession() is expected to do handshake if not completed yet

- src/java/com/wolfssl/provider/jsse/WolfSSLSocket.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLSocketTest.java
This PR makes a small fix to `com.wolfssl.provider.jsse.WolfSSLSocket`.  Inside WolfSSLSocket.close() try to synchronize on `handshakeLock` first to determine if WolfSSLObject has been initialized. There is a case during WolfSSLSocket creation that WolfSSLSocket.super() can call close() before WolfSSLSocket object itself has been initialized.  In this scenario, `handshakeLock` is NULL and `synchronized(handshakeLock)` throws a NullPointerException.
Before this PR, this exception case could be reproduced using the example ClientJSSE.java and trying to connect to a server that is not here / ie underlying Socket connect() fails:
```
$ ./examples/provider/ClientJSSE.sh (without having a server running)
Unable to set FIPS callback without wolfCrypt FIPS code
Unable to set FIPS callback without …
```
> WolfSSLSocket: test if close() called before WolfSSLSocket init

- native/com_wolfssl_WolfSSL.h
- src/java/com/wolfssl/WolfSSL.java
- src/java/com/wolfssl/WolfSSLCertManager.java
- src/java/com/wolfssl/WolfSSLCertificate.java
- src/java/com/wolfssl/WolfSSLCustomUser.java
- src/java/com/wolfssl/WolfSSLException.java
- src/java/com/wolfssl/WolfSSLJNIException.java
- src/java/com/wolfssl/WolfSSLSession.java
- src/java/com/wolfssl/WolfSSLX509StoreCtx.java
- src/java/com/wolfssl/provider/jsse/WolfSSLContext.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngine.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngineHelper.java
- src/java/com/wolfssl/provider/jsse/WolfSSLImplementSSLSession.java
- src/java/com/wolfssl/provider/jsse/WolfSSLInternalVerifyCb.java
- src/java/com/wolfssl/provider/jsse/WolfSSLKeyManager.java
- src/java/com/wolfssl/provider/jsse/WolfSSLKeyX509.java
- src/java/com/wolfssl/provider/jsse/WolfSSLParametersHelper.java
- src/java/com/wolfssl/provider/jsse/WolfSSLProvider.java
- src/java/com/wolfssl/provider/jsse/WolfSSLSNIServerName.java
- src/java/com/wolfssl/provider/jsse/WolfSSLServerSocket.java
- src/java/com/wolfssl/provider/jsse/WolfSSLServerSocketFactory.java
- src/java/com/wolfssl/provider/jsse/WolfSSLSessionContext.java
- src/java/com/wolfssl/provider/jsse/WolfSSLSocket.java
- src/java/com/wolfssl/provider/jsse/WolfSSLSocketFactory.java
- src/java/com/wolfssl/provider/jsse/WolfSSLTrustX509.java
- src/java/com/wolfssl/provider/jsse/WolfSSLX509.java
- src/java/com/wolfssl/provider/jsse/WolfSSLX509X.java
- src/java/com/wolfssl/provider/jsse/adapter/WolfSSLJDK8Helper.java
- src/java/com/wolfssl/wolfcrypt/ECC.java
- src/java/com/wolfssl/wolfcrypt/RSA.java
This PR updates missing Javadocs.  This fixes build warnings when building the Javadocs on newer JDK distributions (ex: JDK 17).
> update missing Javadocs

- IDE/Android/app/src/main/cpp/CMakeLists.txt
- native/com_wolfssl_WolfSSL.c
- native/com_wolfssl_WolfSSL.h
- platform/android_aosp/wolfssl/Android.mk
- src/java/com/wolfssl/WolfSSL.java
This PR removes IDEA wrapper support. Native wolfSSL removed support for IDEA with Pull Request https://github.com/wolfSSL/wolfssl/pull/4806.
If this is a feature that you are/were using, please contact wolfSSL at [facts@wolfssl.com](mailto:facts@wolfssl.com).
> Remove IDEA support

- native/com_wolfssl_WolfSSL.c
- native/com_wolfssl_WolfSSLCertManager.c
- native/com_wolfssl_WolfSSLCertificate.c
- native/com_wolfssl_WolfSSLContext.c
- native/com_wolfssl_WolfSSLSession.c
- native/com_wolfssl_WolfSSLX509StoreCtx.c
This PR fixes a few typecasting issues, cleans up native argument checking, and handles initial type casting of wolfSSL structure pointers up front in native functions before use or doing argument checking.
Most of this PR is cleanup as described above.  Doing the structure pointer casting once on function enter will make it less likely casting issues will come up in the future.  In some cases this also reduces the number of casts done in a single function.
This PR does fix runtime issues that can be seen on some platforms when the representation of a pointer stored in a jlong happens to be negative, but we check the value of it against "<= 0" before type casting it back to a structure pointer type.
For example, below is one bug that existed prior to this PR. `sslPtr` was being passed in …
> Fix possible typecasting issues, typecast cleanup in native functions

- native/com_wolfssl_WolfSSLSession.c
- native/com_wolfssl_WolfSSLSession.h
- src/java/com/wolfssl/WolfSSLSession.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngine.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngineHelper.java
- src/java/com/wolfssl/provider/jsse/WolfSSLSocket.java
This PR adds support for handling Socket timeout values for native SSL_connect() and SSL_write() with socketSelect().
> Support Socket timeout for SSL_connect() and SSL_write() in wolfJSSE

- native/com_wolfssl_WolfSSLSession.c
- src/java/com/wolfssl/WolfSSLCertificate.java
This PR addresses a few missed casting cleanup issues, related to https://github.com/wolfSSL/wolfssljni/pull/98.
On some platforms, pointers stored into Java long types can make that value negative.  As such, we should be comparing against 0 (NULL) for native failure instead of <= 0.
> Casting cleanup, Java side

- native/com_wolfssl_WolfSSL.h
- native/com_wolfssl_WolfSSLSession.c
- src/java/com/wolfssl/WolfSSL.java
- src/java/com/wolfssl/WolfSSLSession.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngine.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngineHelper.java
- src/java/com/wolfssl/provider/jsse/WolfSSLImplementSSLSession.java
- src/java/com/wolfssl/provider/jsse/WolfSSLSocket.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLServerSocketTest.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLTestFactory.java
- src/test/com/wolfssl/test/WolfSSLSessionTest.java
This PR adjusts WolfSSLSession.connect() to correctly throw a SocketTimeoutException when the underlying native call to `socketSelect()` detects a socket timeout and returns `WOLFJNI_TIMEOUT`. This will result in correct behavior at the JSSE level from WolfSSLSocket.startHandshake(), which was previously not detecting the timeout correctly.
This PR also fixes `ant test` issues when tested against wolfSSL master, including:
- Generate pseudo session ID values if session tickets are being used. Not only for TLS 1.3, as before.
- Fix SSLEngine behavior for SSL_shutdown() now that newer wolfSSL's define `WOLFSSL_ERROR_CODE_OPENSSL` automatically when `OPENSSL_ALL` is defined.
- Correct error string detection for test in WolfSSLServerSocketTest. Newer wolfSSL has modified the error string …
> Throw SocketTimeoutException from WolfSSLSession.connect()

- native/com_wolfssl_WolfSSL.h
- native/com_wolfssl_WolfSSLSession.c
- native/com_wolfssl_WolfSSLSession.h
- src/java/com/wolfssl/WolfSSL.java
- src/java/com/wolfssl/WolfSSLSession.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngine.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngineHelper.java
- src/java/com/wolfssl/provider/jsse/WolfSSLParametersHelper.java
- src/java/com/wolfssl/provider/jsse/adapter/WolfSSLJDK8Helper.java
- src/test/com/wolfssl/test/WolfSSLSessionTest.java
This PR adds support to WolfSSLEngine for the `getApplicationProtocol()` method.  Fixes test case with Undertow server.
Other items added/changed as part of this PR:
- Wrap native `wolfSSL_UseALPN()` function at JNI level
- Fix compile error with wolfSSL versions less than 4.2.0 where `wolfSSL_set_alpn_protos()` was not available.
- Add support to WolfSSLParameters for `getApplicationProtocols()` and `setApplicationProtocols()` if using Java 8 or later.   These APIs are not available in SSLParameters for JDK versions less than 1.8.  As such, test cases have been omitted for now until we can add support to test harness for conditional JDK version builds.  Same situation as SNI related get/set methods in SSLParameters.
> Add support for SSLEngine.getApplicationProtocol()

- src/java/com/wolfssl/provider/jsse/adapter/WolfSSLJDK8Helper.java
This PR fixes one warning that may show up in WolfSSLJDK8Helper.java:
```
compile-nativeheaderdir:
[javac] Compiling 54 source files to /var/lib/jenkins/workspace/nightly-wolfssljni-jsse-extra/wolfjsse_tests/wolfssljni/build
[javac] /var/lib/jenkins/workspace/nightly-wolfssljni-jsse-extra/wolfjsse_tests/wolfssljni/src/java/com/wolfssl/provider/jsse/adapter/WolfSSLJDK8Helper.java:135: warning: non-varargs call of varargs method with inexact argument type for last parameter;
[javac]                         m.invoke(out, appProtos);
[javac]                                       ^
[javac]   cast to Object for a varargs call
[javac]   cast to Object[] for a non-varargs call and to suppress this warning
[javac] 1 warning
```
> Fix varargs warning in WolfSSLJDK8Helper.java

- native/com_wolfssl_WolfSSL.c
- native/com_wolfssl_WolfSSL.h
- native/com_wolfssl_WolfSSLCertManager.c
- native/com_wolfssl_WolfSSLCertificate.c
- native/com_wolfssl_WolfSSLContext.c
- native/com_wolfssl_WolfSSLSession.c
- src/java/com/wolfssl/WolfSSL.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLX509Test.java
- src/test/com/wolfssl/test/WolfSSLCertificateTest.java
- src/test/com/wolfssl/test/WolfSSLContextTest.java
This PR fixes native JNI builds when wolfSSL has been compiled with `--disable-filesystem`, or `-DNO_FILESYSTEM`.
> Native JNI fixes for NO_FILESYSTEM

- src/java/com/wolfssl/provider/jsse/WolfSSLEngine.java
- src/java/com/wolfssl/provider/jsse/WolfSSLImplementSSLSession.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLEngineTest.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLTestFactory.java
This PR makes changes to WolfSSLEngine.java including:
- Adds support for application data sizes to wrap() that are larger than a TLS record size, chunks data.
- Refactor handshake status behavior to be more inline with SunJSSE for interop
- Splits behavior between handshake and application data to better tell handshake status
- Adds more verbose logging with new system property `wolfsslengine.debug`
- Adds test case for `setUseClientMode()` and now throws InvalidArgumentException when not set before wrap/unwrap
**Testing**
This was tested against:
A. Built-in unit tests as well as a version of Oracle's `SSLEngineSimpleDemo.java` [1].
B. Our own Undertow server test. Undertow uses SSLEngine internally and acts as a good regression test [2].
C. Added SSLEngineTest.java test case for larger …
> SSLEngine: support large application data, refactor for better status messages

- IDE/Android/.idea/gradle.xml
- IDE/Android/.idea/misc.xml
- IDE/Android/README.md
- IDE/Android/app/build.gradle
- IDE/Android/app/src/main/AndroidManifest.xml
- IDE/Android/app/src/main/java/com/example/wolfssl/MainActivity.java
- IDE/Android/app/src/main/res/layout/activity_main.xml
- README.md
- build.xml
- src/java/com/wolfssl/provider/jsse/WolfSSLProvider.java
This PR includes fixes from v1.10 release cycle and updates to README for v1.10 changes:
- Updates README.md with v1.10 ChangeLog info
- Bumps version in WolfSSLProvider.java to 1.10
- Adds jar manifest info in build.xml
- Updates Android Studio IDE example project to Android 11 (SDK 30), for SSLParameters ALPN API access
> Prep for 1.10.0 Release

- README.md
- native/com_wolfssl_WolfSSL.c
- native/com_wolfssl_WolfSSLContext.c
- native/com_wolfssl_WolfSSLContext.h
- native/com_wolfssl_WolfSSLSession.c
- native/com_wolfssl_WolfSSLSession.h
- src/java/com/wolfssl/WolfSSLContext.java
- src/java/com/wolfssl/WolfSSLSession.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngineHelper.java
- src/test/com/wolfssl/test/WolfSSLContextTest.java
- src/test/com/wolfssl/test/WolfSSLSessionTest.java
This PR wraps the native wolfSSL API for secure renegotiation.
It also modifies wolfJSSE to automatically call `wolfSSL_UseSecureRenegotiation(WOLFSSL* ssl)` if secure renegotiation support has been compiled into the native wolfSSL library.  If native wolfSSL has not had secure renegotiation enabled at compile time, wolfJSSE will not support secure renegotiation.
We have seen some servers that expect secure renegotiation to be enabled and available from the client, otherwise the connection is shut down with a fatal handshake alert.
This has been tested with:
- OpenJDK 7, 8, 15
- Amazon Coretto 17
- Oracle JDK 18
- Android 6 (Ubuntu 14.04)
> wrap secure renegotiation API, enable in wolfJSSE

- src/java/com/wolfssl/provider/jsse/WolfSSLSocket.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLServerSocketTest.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLSocketTest.java
This PR adds support for calling `SSLSocketFactory.createSocket(Socket s, String host, int port, boolean autoClose)` with host as null.
We remove the creation of a `new InetSocketAddress` at that point, since it is never used by wolfJSSE currently.
> Support null host with createSocket(Socket, String, int, boolean)

- src/java/com/wolfssl/provider/jsse/WolfSSLSocket.java
This PR is a follow up to https://github.com/wolfSSL/wolfssljni/pull/111.  The class variable `InetSocketAddress address` does not need to be a class variable inside WolfSSLSocket.java.  It's only set and used locally within two `connect()` methods.
> SSLSocket: change class variable InetSocketAddress to method local scope

- src/java/com/wolfssl/provider/jsse/WolfSSLEngine.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLEngineTest.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLServerSocketTest.java
This PR makes fixes to wolfJSSE's SSLEngine implementation (WolfSSLEngine.java), including:
- Set status to `BUFFER_OVERFLOW` when unwrap() needs more output buffer space
- Fix for setting of client-side handshake FINISHED status
- Fixes setting of output data across multiple output buffers
- Fixes reported bytes consumed and produced
- Set status to `BUFFER_UNDERFLOW` if the SSLEngine needs more data to proceed
- Set the handshake status in SSLEngine.beginHandshake(), only initialize handshake once
- Add synchronization lock around native WOLFSSL calls (read/write/connect/accept/etc)
- Add extra synchronization tag on some additional functions
This PR also fixes a WolfSSLServerSocketTest which was failing after native wolfSSL updated an error code and string for a specific failure case. …
> Fixes and Cleanup to SSLEngine Implementation

- src/java/com/wolfssl/provider/jsse/WolfSSLEngine.java
SSLEngine parent class's getHandshakeSession() doesn't have abstract attribute on it. Therefore, we should not define @Override annotation on inherited class method.
This causes compile error on android-6.0.1_r22 branch. Found at google cloud VM
> fix compile error due to Override annotation

- IDE/Android/README.md
- README.md
This PR adds instructions to `IDE/Android/README.md` on how to update source symlinks for Windows users. The symlinks are Unix/Linux relative symlinks which won't work out of the box on Windows.
> Add Instructions to Update symlink for Android Studio Windows Users

- src/java/com/wolfssl/provider/jsse/WolfSSLKeyX509.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLKeyX509Test.java
This PR makes one small fix to `X509KeyManager.getCertificateChain()` to correctly return `null` if the input alias is `null`. Without this change a NullPointerException gets thrown.
Also adds a small unit test to protect against regression.
> X509KeyManager.getCertificateChain(): return null if alias is null

- src/java/com/wolfssl/WolfSSLCertificate.java
This PR adds locking/synchronization around use of internal state `this.active` and object `this.x509Ptr`.
This PR also adds a check if WolfSSLCertificate owns the internal native pointer to `WOLFSSL_X509`.  If it does not own the pointer, that pointer/memory should not be freed by the WolfSSLCertificate object.
> Add state/object locking in WolfSSLCertificate

- src/java/com/wolfssl/provider/jsse/WolfSSLEngine.java
`SSLEngine.getHandshakeStatus()` should try to update the current status before returning to the caller. Some callers loop around this to take further action based on the value.
> SSLEngine: update HandshakeStatus inside getHandshakeStatus()

- java.sh
Add support to `java.sh` script to use a pre-set `JAVA_HOME` environment variable instead of trying to auto-detect location of Java home directory.
This also removes some defines that were being set to `cflags`, which are not needed since those should be picked up via inclusion of `<wolfssl/options.h>`.
> Add JAVA_HOME support in java.sh

- java.sh
This PR adds support for using a custom wolfSSL library name in `java.sh`. Some users compile native wolfSSL using the `--with-libsuffix` configure option, which will change the wolfSSL library name.
Adding a second argument to `java.sh` allows users to pass in the wolfSSL library name to link against for the native JNI shared library.
> Support custom wolfSSL library name in java.sh

- src/java/com/wolfssl/provider/jsse/WolfSSLTrustX509.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLTrustX509Test.java
Returns null now in the case that the trust manager is used before initialized. Note that this is not exactly how SunJSSE does it. For example the following was the result of removing the init() call in examples/provider/ClientJSSE.java and using the SunJSSE provider on Ubuntu:
```
$ ./examples/provider/ClientJSSE.sh 
Unable to set FIPS callback without wolfCrypt FIPS code
java.lang.IllegalStateException: TrustManagerFactoryImpl is not initialized
at java.base/sun.security.ssl.TrustManagerFactoryImpl.engineGetTrustManagers(TrustManagerFactoryImpl.java:102)
at java.base/javax.net.ssl.TrustManagerFactory.getTrustManagers(TrustManagerFactory.java:317)
at ClientJSSE.run(ClientJSSE.java:209)
at ClientJSSE.main(ClientJSSE.java:329)
```
With the change in this pull request we try to continue on …
> return null for cert array if trust manager is not initialized

- src/java/com/wolfssl/provider/jsse/WolfSSLDebug.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngine.java
This PR adds a `logHex()` method to the `WolfSSLDebug` class, to be used for printing byte arrays as hex.  Synchronizes this method and prints Thread ID for easier multi-threaded debugging.
Removes a similar private method from WolfSSLEngine, and switches to call new method instead.
> Add debug method for printing hex with Thread ID

- native/com_wolfssl_WolfSSLSession.c
- src/java/com/wolfssl/WolfSSLCertificate.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngine.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLEngineTest.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLTestFactory.java
This PR adds synchronization around two internal buffers in `WolfSSLEngine.java` used for send/recv, `toSend` and `toRead`, and changes two variables in native `NativeSSLIORecvCb()` and `NativeSSLIOSendCb` that were not thread safe due to being marked static.
More extended threading test of SSLEngine has been added to JUnit tests to help prevent regression.
Resolves ZD #16011.
> SSLEngine: synchronize access to internal send/recv buffers

- java.sh
This PR appends `$WOLFSSL_INSTALL_DIR/lib64` to the library path in `java.sh` after `$WOLFSSL_INSTALL_DIR/lib`. Some systems use `lib64` as the default library installation location.
> java.sh: add lib64 to library path for libwolfssl

- examples/provider/README.md
Same fix as in the documentation: update example instructions for ClientSSLSocket.java example to reflect appropriate truststore to run example.
> Update example instructions in README

- examples/provider/MultiThreadedSSLClient.java
- native/com_wolfssl_WolfSSLContext.c
- native/com_wolfssl_WolfSSLContext.h
- native/com_wolfssl_WolfSSLSession.c
- native/com_wolfssl_WolfSSLSession.h
- src/java/com/wolfssl/WolfSSLContext.java
- src/java/com/wolfssl/WolfSSLSession.java
- src/java/com/wolfssl/provider/jsse/WolfSSLContext.java
- src/java/com/wolfssl/provider/jsse/WolfSSLCustomUser.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngineHelper.java
- src/java/com/wolfssl/provider/jsse/WolfSSLServerSocket.java
- src/java/com/wolfssl/provider/jsse/WolfSSLServerSocketFactory.java
- src/java/com/wolfssl/provider/jsse/WolfSSLSocketFactory.java
- src/java/com/wolfssl/provider/jsse/WolfSSLUtil.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLContextTest.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLSocketTest.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLTestFactory.java
- src/test/com/wolfssl/test/WolfSSLContextTest.java
This PR adds support for:
1. Partial support for `jdk.tls.disabledAlgorithms` security property, including the ability to disable SSL/TLS protocol versions and set RSA/ECC/DH minimum key sizes. This security property would be set in the OS-level `java.security` file and is a comma-delimited string.  For example:
```
jdk.tls.disabledAlgorithms=SSLv3, TLSv1.1, DH keySize < 1024, EC keySize < 224, RSA keySize < 1024
```
2. New wolfJSSE-specific security property `wolfjsse.enabledCipherSuites`, which allows a user to restrict the enabled cipher suites to those listed in this system property. Suites used may be a subset of the ones included in this property, but the user/application will not be able to override or add additional suites at runtime without changing the system property.  This …
> Additional Security Property Support

- README.md
- src/java/com/wolfssl/provider/jsse/WolfSSLDebug.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngine.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLEngineTest.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLTestFactory.java
This PR refactors `WolfSSLEngine.java` to make the `unwrap()` operation more efficient by reading bytes directly from the incoming `ByteBuffer`, instead of internally copying and buffering incoming data. This should increase performance and reduce memory usage by eliminating local copies/caching.
This also fixes an edge case where `BUFFER_OVERFLOW` status should be returned when there is remaining input data, but no available output space. Returning this status should cause the calling code to clear/reset the output buffer.
Lastly, this PR splits the SSLEngine I/O debugging for bytes sent/received into a new System property (`wolfsslengine.io.debug`). Printing out all bytes sent/received for normal `wolfsslengine.debug` negatively impacts the connection time enough that it causes some …
> Refactor SSLEngine unwrap() Operation

- native/com_wolfssl_WolfSSLSession.c
- native/com_wolfssl_WolfSSLSession.h
- src/java/com/wolfssl/WolfSSLSession.java
- src/java/com/wolfssl/provider/jsse/WolfSSLAuthStore.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngine.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngineHelper.java
- src/java/com/wolfssl/provider/jsse/WolfSSLImplementSSLSession.java
- src/test/com/wolfssl/test/WolfSSLContextTest.java
Prior to this PR, wolfJSSE called down to `wolfSSL_get_session()` for saving session state to be used in the future and re-set for resumption using `wolfSSL_set_session()`.  In versions of wolfSSL after 5.2.0, `wolfSSL_get_session()` returns a pointer that will be freed on `wolfSSL_free()`.  This switches wolfJSSE to call `wolfSSL_get1_session()` instead, and then frees the pointer when finished with `wolfSSL_SESSION_free()`.
Additional changes in this PR include:
- Add synchronization lock around WolfSSLAuthStore store (storeLock)
- Doesn't add session to Java cache if session ID is all zeros
- Correctly add session to Java cache in when `WolfSSLEngineHelper.saveSession()` is called
- Saves session to Java cache when SSLEngine finishes TLS handshake, for proper resumption
Tested with …
> JNI/JSSE: call wolfSSL_get1_session() for saving session in WolfSSLAuthStore

- src/java/com/wolfssl/provider/jsse/WolfSSLTrustX509.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLTrustX509Test.java
This PR includes a fix for `WolfSSLTrustX509.certManagerVerify()`, which gets called from `X509TrustManager.checkClientTrusted()` and `X509TrustManager.checkServerTrusted()`. If the TrustManager KeyStore contains a root CA, and the peer also sends the root CA in the cert chain, we should not add the root CA twice to the returned `X509Certificate[]`.
ZD 16230
> JSSE: do not return duplicate root CA in chain from X509TrustManager.checkClient/ServerTrusted()

- src/java/com/wolfssl/provider/jsse/WolfSSLSocket.java
- src/java/com/wolfssl/provider/jsse/WolfSSLSocketFactory.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLSocketTest.java
This PR modifies wolfJSSE's `WolfSSLSocket` implementation by registering native wolfSSL I/O callbacks which call a wrapped `java.net.Socket` or subclassed object's InputStream and OutputStream if setting the internal `SocketImpl` file descriptor to native wolfSSL fails.
Some subclasses of `java.net.Socket` do not initialize the internal file descriptor if they will be handling I/O differently. For these cases we need to use I/O callbacks to read and write from the provided InputStream and OutputStream.
A test case has been added where we create our own subclass of `java.net.Socket` that does not have the internal file descriptor set.
Related to ZD 15902, where Socket subclass was of type `com.microsoft.sqlserver.jdbc.TDSChannel$ProxySocket`.  Customer confirmed this has fixed the …
> SSLSocket: fall back to I/O callbacks with Input/OutputStream if setting internal file descriptor fails

- src/java/com/wolfssl/WolfSSL.java
- src/java/com/wolfssl/WolfSSLContext.java
- src/java/com/wolfssl/WolfSSLSession.java
This PR cleans up Javadoc warnings when compiled with Java 17.
> Clean up Javadoc warnings (Java 17)

- native/com_wolfssl_WolfSSLSession.c
- native/com_wolfssl_WolfSSLSession.h
- src/java/com/wolfssl/WolfSSLSession.java
- src/java/com/wolfssl/provider/jsse/WolfSSLAuthStore.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngine.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngineHelper.java
- src/java/com/wolfssl/provider/jsse/WolfSSLImplementSSLSession.java
- src/java/com/wolfssl/provider/jsse/WolfSSLSocket.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLEngineTest.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLSessionContextTest.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLTestFactory.java
This PR contains a variety of JSSE-level fixes which help fix compatibility with Spring Boot, RabbitMQ, session resumption, and SSLEngine usage.
- Previous PR (https://github.com/wolfSSL/wolfssljni/pull/142) added synchronization around native pointer use. We need to loosen locking on WolfSSLSession.read/write() since it's already locking/unlocking a mutex at the native JNI layer.  With the existing sslLock synchronization around write/read(), we can get stuck in a timeout situation where we are waiting on read() for example, but data needs to be written with write() before state can continue. This can lead to the peer timing out and closing the socket too early (https://github.com/wolfSSL/wolfssljni/pull/144/commits/4f2df6db81b1b6b78ebf4f54454bff7f410a0aa1)
- Cache the peer certificate …
> Fixes for SSLSocket, SSLEngine, session resumption, and synchronization

- src/java/com/wolfssl/provider/jsse/WolfSSLDebug.java
This PR adds a timestamp to the wolfJSSE debug logs, making it easier to compare log entries to Wireshark captures or other timestamped logs/events.
Timestamp looks similar to this:
```
2023-09-08 15:56:51.608 [wolfJSSE INFO: TID 1: WolfSSLKeyX509] entered chooseClientAlias()
2023-09-08 15:56:51.609 [wolfJSSE INFO: TID 1: WolfSSLKeyX509] entered getPrivateKey(), alias: server-ecc
2023-09-08 15:56:51.611 [wolfJSSE INFO: TID 1: TLSV12_Context] loaded private key from KeyManager (alias: server-ecc)
2023-09-08 15:56:51.611 [wolfJSSE INFO: TID 1: WolfSSLKeyX509] entered getCertificateChain(), alias: server-ecc
2023-09-08 15:56:51.611 [wolfJSSE INFO: TID 1: TLSV12_Context] loaded certificate chain from KeyManager (length: 1)
2023-09-08 15:56:51.611 [wolfJSSE INFO: TID 1: TLSV12_Context] entered …
```
> Add timestamp to wolfJSSE debug logs

- native/com_wolfssl_WolfSSL.c
- native/com_wolfssl_WolfSSL.h
- native/com_wolfssl_WolfSSLContext.c
- native/com_wolfssl_WolfSSLContext.h
- src/java/com/wolfssl/WolfSSL.java
- src/java/com/wolfssl/WolfSSLContext.java
- src/java/com/wolfssl/provider/jsse/WolfSSLContext.java
- src/java/com/wolfssl/provider/jsse/WolfSSLProvider.java
Adds native wolfSSL crypto callback (CryptoCb) support when using wolfJSSE (WolfSSLProvider).
Applications can register a native device and set a device ID (devId) for WolfSSLProvider when creating the provider, ie:
```
WolfSSLProvider wolfProv = new WolfSSLProvider();
wolfProv.registerDevId(1001);
wolfProv.setDevId(1001);
Security.insertProviderAt(wolfProv, 1);
```
This will cause all new SSLContext (WolfSSLContext) objects to be set using this device ID.  It will also call the native JNI API `Java_com_wolfssl_WolfSSL_wc_1CryptoCb_1RegisterDevice()` in `native/com_wolfssl_WolfSSL.c` which will register the native crypto callback function. There is a default callback stub implemented in `native/com_wolfssl_WolfSSL.c` called `DefaultNativeCryptoDevCb()` which will be registered if …
> JNI/JSSE: add support for wolfSSL CryptoCb in WolfSSLProvider and WolfSSLContext

- src/java/com/wolfssl/provider/jsse/WolfSSLAuthStore.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngineHelper.java
- src/java/com/wolfssl/provider/jsse/WolfSSLImplementSSLSession.java
- src/java/com/wolfssl/provider/jsse/WolfSSLSocket.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLSocketTest.java
This PR makes some threading fixes to `SSLSocket` and related classes.  Including:
- Adjusts the `WolfSSLInputStream` and `WolfSSLOutputStream` classes in `WolfSSLSocket` to protect calls to `ssl.read/write` with the `ioLock` in `WolfSSLSocket`.  Prior to this each had their own `read/writeLock`, but native `WOLFSSL` structure access from read/write operations should be protected by the same lock.
- Removes a `WolfSSLImplementSSLSession` object / `WOLFSSL_SESSION` struct from Java-side client cache when a SSLSocket begins a resumption attempt. After the handshake finishes, the SSLSocket puts an updated entry back into the cache. Prior to this, the session object was left in the cache, which for TLS 1.3 concurrent resumption attempts could result in "bad binder" / "313" errors.
- Adds an …
> SSLSocket threading fixes, TLS 1.3 session cache fixes, extended threading test

- build.xml
- java.sh
This PR standardizes the native JNI shared library on OSX to `.dylib` extension, which matches OSX shared library naming. Some Java versions won't find `libwolfssljni.jnilib` if installed unless it is named `libwolfssljni.dylib` instead.
> Standardize JNI library name on OSX to .dylib

- .gitignore
- README.md
- native/com_wolfssl_WolfSSLSession.c
- pom.xml
- src/test/com/wolfssl/provider/jsse/test/WolfSSLServerSocketTest.java
- src/test/com/wolfssl/test/WolfSSLContextTest.java
- src/test/com/wolfssl/test/WolfSSLSessionTest.java
This PR adds initial Maven build support for wolfSSL JNI/JSSE.  This adds an alternative build system for users who want to build with Maven rather than ant.  See `README.md` for build instructions.
Note: this PR does not support building the example application with Maven. That functionality may come in a future PR.
> Add initial Maven build support

- native/com_wolfssl_WolfSSL.c
- native/com_wolfssl_WolfSSL.h
- native/com_wolfssl_WolfSSLSession.c
- native/com_wolfssl_WolfSSLSession.h
- src/java/com/wolfssl/WolfSSL.java
- src/java/com/wolfssl/WolfSSLSession.java
- src/java/com/wolfssl/provider/jsse/WolfSSLAuthStore.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngine.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngineHelper.java
- src/java/com/wolfssl/provider/jsse/WolfSSLImplementSSLSession.java
- src/java/com/wolfssl/provider/jsse/WolfSSLTrustX509.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLTrustX509Test.java
This PR:
- Exposes a JNI method in `WolfSSL.java` that retrieves the status of if `WOLFSSL_TRUST_PEER_CERT` was defined in native wolfSSL or not.
- Modifies `WolfSSLTrustX509.getAcceptedIssuers()` when adding CA/root certs to array to add them if either `CA:TRUE` Basic Constraint is set or `WOLFSSL_TRUST_PEER_CERT` has been defined.
The SunJSSE X509TrustManager.getAcceptedIssuers() implementation simply returns all certificates in the supplied KeyStore. Our wolfJSSE implementation was always more restricted, mandating the `CA:TRUE` extension be set. But for compatibility and interop, this change allows use cases where the peer certificate is self-signed but does not have the CA:TRUE extension set.
- Locks native `WOLFSSL` session lock when `wolfSSL_get_session()` and …
> JNI/JSSE: WOLFSSL_TRUST_PEER_CERT support, session resumption fixes

- examples/provider/ClientJSSE.java
This PR makes a small fix to the example JSSE client (`ClientJSSE.java`) to correctly send an HTTP GET message when the user has used the `-g` option.
> Fix example JSSE client for resume case when sending HTTP GET

- native/com_wolfssl_WolfSSL.c
- native/com_wolfssl_WolfSSL.h
- src/java/com/wolfssl/WolfSSL.java
- src/java/com/wolfssl/WolfSSLSession.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngine.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngineHelper.java
- src/test/com/wolfssl/test/WolfSSLSessionTest.java
- src/test/com/wolfssl/test/WolfSSLTest.java
This PR modified JNI/JSSE code to throw a `SocketException` (or propagated as `SSLException` in JSSE) if the native socket `select()` call fails. Previously this was not handled gracefully and ended up in vague error logs. This adds the system `errno` to the `SocketException` message for easier debugging and error resolution for these scenarios.
Related to ZD #16581
> Throw SocketException if native socket select() fails

- src/java/com/wolfssl/provider/jsse/WolfSSLEngineHelper.java
- src/java/com/wolfssl/provider/jsse/WolfSSLSocket.java
This PR refactors some `SSLSocket` and `SSLEngineHelper` code around the usage of `InetAddress`.
Sockets created with the host as an `InetAddress` were previously calling `InetAddress.getHostName()` to set the hostname inside `WolfSSLEngineHelper`. This was used as the key into the session cache (concatenated with the port).  The downside to this approach is that `getHostName()` does a DNS lookup, which in some scenarios can cause performance issues when the DNS server is not available and execution needs to wait for a timeout to occur instead.
This PR refactors `InetAddress.getHostName()` to use `InetAddress.getHostAddress()` and use the IP address for session cache key instead of the hostname. SSLSocket's created using a `String host` will still use that as the session cache key.
We …
> Skip calling InetAddress.getHostName() to avoid DNS lookups when possible

- native/com_wolfssl_WolfSSL.c
- native/com_wolfssl_WolfSSL.h
- native/com_wolfssl_WolfSSLContext.c
- native/com_wolfssl_WolfSSLContext.h
- src/java/com/wolfssl/WolfSSL.java
- src/java/com/wolfssl/WolfSSLContext.java
- src/test/com/wolfssl/test/WolfSSLContextTest.java
This PR wraps the `wolfSSL_CTX_UseSupportedCurve()` API inside the thin JNI wrapper class `com.wolfssl.WolfSSLContext`. Note this is being added to the wolfSSL JNI wrapper and not integrated into the JSSE provider as of this PR.
User API for this from `com.wolfssl.WolfSSLContext` is:
```
public int useSupportedCurves(String[] curveNames);
```
Where `curveNames` is a String array of Strings from the following options. These Strings have been formatted to use similar naming as Java does:
```
String array of ECC curve names to set into the Supported Curve extension. String values should match names from the following list:
"sect163k1", "sect163r1", "sect163r2", "sect193r1",
"sect193r2", "sect233k1", "sect233r1", "sect239k1",
"sect283k1", "sect283r1", "sect409k1", "sect409r1",
"sect571k1", …
```
> Wrap wolfSSL_CTX_UseSupportedCurve() in com.wolfssl.WolfSSLContext

- native/com_wolfssl_WolfSSLContext.c
- native/com_wolfssl_wolfcrypt_EccKey.c
This PR corrects a few heap pointers in calls to `XFREE()`.  Noticed when doing a compile on Debian 12.
> JNI: correct heap pointers for a few XFREE calls in JNI code

- native/com_wolfssl_WolfSSLCertificate.c
- native/com_wolfssl_WolfSSLCertificate.h
- native/com_wolfssl_WolfSSLSession.c
- native/com_wolfssl_WolfSSLSession.h
- src/java/com/wolfssl/WolfSSLCertificate.java
- src/java/com/wolfssl/WolfSSLSession.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngine.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngineHelper.java
- src/java/com/wolfssl/provider/jsse/WolfSSLImplementSSLSession.java
- src/java/com/wolfssl/provider/jsse/WolfSSLInternalVerifyCb.java
- src/java/com/wolfssl/provider/jsse/WolfSSLParameters.java
- src/java/com/wolfssl/provider/jsse/WolfSSLParametersHelper.java
- src/java/com/wolfssl/provider/jsse/WolfSSLSocket.java
- src/java/com/wolfssl/provider/jsse/WolfSSLTrustX509.java
- src/java/com/wolfssl/provider/jsse/adapter/WolfSSLJDK8Helper.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLTrustX509Test.java
This PR implements `javax.net.ssl.X509ExtendedTrustManager`, which will automatically do internal hostname verification when the Endpoint Identification Algorithm has been set to `HTTPS` inside `SSLParameters`, ie:
```
SSLSocket sock = ...
SSLParameters params = sock.getSSLParameters();
params.setEndpointIdentificationAlgorithm("HTTPS");
sock.setSSLParameters(params);
```
Hostname verification matches SunJSSE behavior and if available compares the value set into the Server Name Indication (SNI) first, then falls back to compare against the peer hostname.
A few success/failure tests have been added in `src/test/com/wolfssl/provider/jsse/test/WolfSSLTrustX509Test.java` for both `SSLSocket` and `SSLEngine` use cases.
This PR also makes some supporting changes including:
- Wrap native …
> Add implementation of javax.net.ssl.X509ExtendedTrustManager

- native/com_wolfssl_WolfSSLContext.c
- native/com_wolfssl_WolfSSLContext.h
- src/java/com/wolfssl/WolfSSLContext.java
- src/java/com/wolfssl/provider/jsse/WolfSSLAuthStore.java
- src/java/com/wolfssl/provider/jsse/WolfSSLImplementSSLSession.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLTrustX509Test.java
This PR fixes `SSLSession.getPeerCertificates()` to correctly call `ssl.getPeerCertificate()` first before returning the cached peer certificate from a previous successful handshake on the same `WOLFSSL_SESSION`.
In cases where the client tries to resume using a `WOLFSSL_SESSION` from a previous successful connection, the `WolfSSLImplementSSLSession` will have the peer certificate cached (on purpose for resume cases where no peer cert is sent, but Java callers still need access to the peer cert).  But, since that session/connection may fall back to a new handshake, we need to call `ssl.getPeerCertificate()` first to see if we have a peer certificate at our native wolfSSL level first, before defaulting back to the Java cached version.
Test case has been included here for this scenario, and …
> SSLSession fix for getPeerCertificates() and cached cert

- native/com_wolfssl_WolfSSL.c
- native/com_wolfssl_WolfSSL.h
- native/com_wolfssl_WolfSSLContext.c
- native/com_wolfssl_WolfSSLContext.h
- src/java/com/wolfssl/WolfSSL.java
- src/java/com/wolfssl/WolfSSLContext.java
- src/test/com/wolfssl/test/WolfSSLContextTest.java
- src/test/com/wolfssl/test/WolfSSLTest.java
This PR wraps three native wolfSSL APIs in the thin wolfSSL JNI layer:
- `wolfSSL_CTX_set_groups()` inside `com.wolfssl.WolfSSLContext`
- `wolfTLSv1_3_client_method()` inside `com.wolfssl.WolfSSL`
- `wolfTLSv1_3_server_method()` inside `com.wolfssl.WolfSSL`
> JNI: wrap wolfSSL_CTX_set_groups(), wolfTLSv1_3_client/server_method()

- src/java/com/wolfssl/provider/jsse/WolfSSLEngine.java
This PR modifies `WolfSSLEngine (SSLEngine)` to remove the attempt to save the session right after `ssl.accept/connect()`. We already store the session on connection closure, which is the proper way to do it since in TLS 1.3 the Session Ticket can come after the handshake finishes and may not be available yet.
This matches behavior of `WolfSSLSocket (SSLSocket)`, and also fixes the sporadically failing ExtendedSSLEngineTest with `ant test`.
> JSSE: SSLEngine: save session only on connection shutdown

- build.xml
- examples/MyALPNSelectCallback.java
- examples/Server.java
- native/com_wolfssl_WolfSSL.h
- native/com_wolfssl_WolfSSLSession.c
- native/com_wolfssl_WolfSSLSession.h
- src/java/com/wolfssl/WolfSSL.java
- src/java/com/wolfssl/WolfSSLALPNSelectCallback.java
- src/java/com/wolfssl/WolfSSLSession.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngine.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngineHelper.java
- src/java/com/wolfssl/provider/jsse/WolfSSLSocket.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLSocketTest.java
This PR implements support for the following ALPN API's from the `SSLEngine` and `SSLSocket` classes, as well as supporting JNI level changes and test cases.
```
public synchronized String getHandshakeApplicationProtocol();
public synchronized BiFunction<SSLEngine,List<String>,String>
getHandshakeApplicationProtocolSelector();
public synchronized void setHandshakeApplicationProtocolSelector(
BiFunction<SSLEngine,List<String>,String> selector);
```
Tested against added JUnit tests as well as the following SunJSSE tests:
```
ALPN/SSLEngineAlpnTest.java
ALPN/SSLSocketAlpnTest.java
``` 
This fixes compatibility with Netty.
ZD #16581
> JSSE: add SSLSocket/Engine support get/setHandshakeApplicationProtocolSelector()

- native/com_wolfssl_WolfSSL.c
- scripts/infer.sh
- src/java/com/wolfssl/WolfSSL.java
- src/java/com/wolfssl/provider/jsse/WolfSSLContext.java
- src/java/com/wolfssl/provider/jsse/WolfSSLDebug.java
- src/java/com/wolfssl/provider/jsse/WolfSSLNativeLoggingCallback.java
- src/java/com/wolfssl/provider/jsse/WolfSSLProvider.java
Native wolfSSL debug logs are enabled from the Java layer by setting the `wolfssl.debug` System property to "true".  This was previously detected and set inside the `WolfSSLProvider` class which worked well for applications that set the System property before the provider was registered.  But for applications that set the `wolfssl.debug` system property **after** the provider has been registered (ie: when installing at the system level), this was not picked up.
This PR also detects and enables native wolfSSL debug logging when a new `WolfSSLContext / SSLContext` is created, which will allow native debug logs to more easily show up for users who install at a system level.
This PR also registers a default native logging callback from Java with native wolfSSL so that native logs go out …
> Refactor native debug log enablement, register Java native logging callback

- examples/Client.java
- examples/Server.java
- native/com_wolfssl_WolfSSL.c
- native/com_wolfssl_WolfSSL.h
- native/com_wolfssl_WolfSSLContext.c
- native/com_wolfssl_WolfSSLContext.h
- src/java/com/wolfssl/WolfSSL.java
- src/java/com/wolfssl/WolfSSLContext.java
- src/test/com/wolfssl/test/WolfSSLContextTest.java
This PR:
- Wraps the native `SSL_CTX_set1_sigalgs_list()` API inside `WolfSSLContext`
- Adds a few native feature-detection helper methods to `WolfSSL`
- Expands the JNI-level example client `Client.java` to add support for doing one session resumption with session tickets enabled
- Adds TLS 1.3 version to example JNI `Client.java` and `Server.java`
ZD 17211
> JNI: wrap SSL_CTX_set1_sigalgs_list(), add resume example to JNI Client

- src/java/com/wolfssl/provider/jsse/WolfSSLSocket.java
- Don't proceed with handshake on an unconnected socket.
- Don't return early from handshake if session has been invalidated.
- SSLSocketImpl/UnconnectedSocketWrongExceptions.java
- SSLSocketImpl/InvalidateServerSessionRenegotiate.java
- SSLSocketImpl/ServerRenegoWithTwoVersions.java
> Fix SunJSSE test issues

- native/com_wolfssl_WolfSSLSession.c
This PR makes one change in native JNI code when getting and returning the native `WOLFSSL_SESSION` object to be stored into the Java session cache.
If the connection is using TLS 1.3, only return and store the session if we have the ticket.  Otherwise, we may return an incomplete session object which may cause subsequent resumption attempts to fail.
This issue shows up in our ant tests when native wolfSSL is configured with:
```
cd wolfssl
./autogen.sh
./configure --enable-jni --enable-all
cd wolfssljni
./java.sh
ant
ant test
cat build/reports/TEST-com.wolfssl.provider.jsse.test.WolfSSLJSSETestSuite.txt
...
Testcase: testReuseSession took 0.012 sec
FAILED
failed to create engine
junit.framework.AssertionFailedError: failed to create engine
at …
```
> Check TLS 1.3 session for ticket before saving to Java cache

- .github/workflows/linux-common.yml
- .github/workflows/main.yml
This PR adds GitHub actions for automated testing against various JDK distributions and versions.  Current testing includes:
**wolfSSL ./configure --enable-jni:**
- Test on both Linux (`ubuntu-latest`) and Mac OSX (`macos-latest`)
- Oracle JDK (17, 21)
- Zulu JDK (8, 11, 17, 21)
- Corretto JDK (8, 11, 17, 21)
- Microsoft JDK (11.0.19, 17.0.7, 21.0.0)
**wolfSSL ./configure --enable-jni --enable-all:**
- Test on both Linux (`ubuntu-latest`) and Mac OSX (`macos-latest`)
- Just a sanity check with `--enable-all` used, so only currently testing Zulu JDK 11
> Add initial GitHub actions (Linux, Mac)

- native/com_wolfssl_WolfSSLSession.c
- native/com_wolfssl_WolfSSLSession.h
- src/java/com/wolfssl/WolfSSLContext.java
- src/java/com/wolfssl/WolfSSLSession.java
- src/java/com/wolfssl/provider/jsse/WolfSSLContext.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngine.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngineHelper.java
- src/java/com/wolfssl/provider/jsse/WolfSSLInternalVerifyCb.java
- src/java/com/wolfssl/provider/jsse/WolfSSLParameters.java
- src/java/com/wolfssl/provider/jsse/WolfSSLSocket.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLEngineTest.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLTestFactory.java
This PR makes fixes around how a server-side SSLEngine handles client authentication, as well as how wolfJSSE calls X509KeyManager/X509ExtendedKeyManager objects to choose a private key alias to be used to load the client/server private key:
- `WolfSSLEngine` `setWantClientAuth(true)` was previously too restrictive when `setNeedClientAuth(false)`. This meant that when a server application requested client authentication, but instructed the JSSE layer to not to be a failure if the client did not send a certificate (ie with `setWantClientAuth(true)`, we were requiring the client send a certificate and would error out. This PR loosens that requirement to match expected behavior with `setWantClientAuth()`.
- We recently added support for `X509ExtendedKeyManager`, which has two new methods for …
> Fixes for SSLEngine.setWant/NeedClientAuth() and choosing key alias chooseEngineClient/ServerAlias()

- examples/Client.java
- examples/MyTls13SecretCallback.java
- native/com_wolfssl_WolfSSL.c
- native/com_wolfssl_WolfSSL.h
- native/com_wolfssl_WolfSSLSession.c
- native/com_wolfssl_WolfSSLSession.h
- scripts/infer.sh
- src/java/com/wolfssl/WolfSSL.java
- src/java/com/wolfssl/WolfSSLSession.java
- src/java/com/wolfssl/WolfSSLTls13SecretCallback.java
- src/test/com/wolfssl/test/WolfSSLSessionTest.java
This PR wraps the native wolfSSL API `wolfSSL_set_tls13_secret_cb()` inside the `WolfSSLSession` class. This allows JNI-level users to write and register a TLS 1.3 secret callback for use with Wireshark.
Native wolfSSL needs to be compiled with `-DHAVE_SECRET_CALLBACK`, ie:
```
cd wolfssl-X.X.X
./configure --enable-jni CFLAGS="-DHAVE_SECRET_CALLBACK"
make
sudo make install
```
Java applications need to implement the `com.wolfssl.WolfSSLTls13SecretCallback` interface, for example:
```
class MyTls13SecretCb implements WolfSSLTls13SecretCallback
{
public int tls13SecretCallback(WolfSSLSession ssl, int id,
byte[] secret, Object ctx)
{
/* Implement callback logic, see examples/MyTls13ClientCallback.java for example */
}
}
```
Then provide an instance of that to …
> JNI: wrap wolfSSL_set_tls13_secret_cb() in WolfSSLSession.setTls13SecretCb()

- native/com_wolfssl_WolfSSLX509StoreCtx.c
This PR fixes the free function called in `WolfSSLX509StoreCtx.getDerCerts()` when freeing the `WOLFSSL_STACK*` allocated with `wolfSSL_X509_STORE_GetCerts(WOLFSSL_X509_STORE_CTX*)`.
`wolfSSL_sk_X509_free()` just frees the stack structure, where `wolfSSL_sk_X509_pop_free()` frees each node in the stack then the stack.
`WolfSSLX509StoreCtx.getDerCerts()` is called inside the `WolfSSLInternalVerifyCb` class' `verifyCallback()` method, which will be called when peer verification is conducted inside an SSL/TLS connection with wolfJSSE.
> JNI/JSSE: call wolfSSL_sk_X509_pop_free() in WolfSSLX509StoreCtx.getDerCerts()

- examples/provider/ClientJSSE.java
- examples/provider/MultiThreadedSSLClient.java
- examples/provider/ServerJSSE.java
- native/com_wolfssl_WolfSSLSession.c
- src/java/com/wolfssl/provider/jsse/WolfSSLEngine.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngineHelper.java
- src/java/com/wolfssl/provider/jsse/WolfSSLInternalVerifyCb.java
This PR modifies `SSLEngine` so that it explicitly releases the native wolfSSL verify callback when the SSLEngine enters the CLOSED state.  Once CLOSED, an SSLEngine will not be reused.  From the Javadocs for SSLEngine, "Once an engine is closed, it is not reusable: a new SSLEngine must be created."
The native verify callback is stored as a JNI global variable, which can hold up garbage collection if not explicitly released. Prior to this PR it was being released/freed when the native `WOLFSSL` structure was freed, but with the changes in https://github.com/wolfSSL/wolfssljni/pull/159, the circular reference between SSLEngine and WolfSSLInternalVerifyCallback prevented SSLEngine objects from being garbage collected.
> Release native verify callback with SSLEngine is closed

- native/com_wolfssl_WolfSSLSession.c
- native/com_wolfssl_WolfSSLSession.h
- src/java/com/wolfssl/WolfSSLSession.java
- src/java/com/wolfssl/provider/jsse/WolfSSLSocket.java
This PR adjusts `WolfSSLInputStream` / `WolfSSLOutputStream` inside `WolfSSLSocket` to avoid creating an extra Java byte array if a buffer offset is used in the respective call to `read/write()`.  In doing so, the offset now gets passed down to native JNI and used as the buffer offset instead.  This should reduce Java heap usage for use cases where `read/write()` are called using offsets.
This also fixes one JNI leak in `WolfSSLSession.read/write()` in the rare case that `wolfSSL_get_app_data()` fails and returns NULL.  I don't think we have hit this case, but found via visual inspection of those functions.
> JNI/JSSE: Avoid extraneous Java array allocation in WolfSSLInputStream/OutputStream if offset used

- scripts/infer.sh
- src/java/com/wolfssl/WolfSSLCertificate.java
- src/java/com/wolfssl/WolfSSLContext.java
- src/java/com/wolfssl/WolfSSLSession.java
- src/java/com/wolfssl/WolfSSLX509Name.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngine.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngineHelper.java
- src/java/com/wolfssl/provider/jsse/WolfSSLImplementSSLSession.java
- src/java/com/wolfssl/provider/jsse/WolfSSLSocket.java
This PR includes fixes for potential issues reported by Facebook Infer.  After these changes, Infer returns a clean report:
```
cd wolfssljni
./scripts/infer.sh
Capturing in javac mode...
Found 60 source files to analyze in wolfssljni/infer-out
947/947 [############################################################################] 100% 7.91s
No issues found
```
> Fixes from Infer scan over JNI/JSSE classes

- examples/Client.java
- examples/Server.java
- src/java/com/wolfssl/WolfSSLCertificate.java
- src/java/com/wolfssl/WolfSSLSession.java
- src/java/com/wolfssl/provider/jsse/WolfSSLImplementSSLSession.java
- src/java/com/wolfssl/provider/jsse/WolfSSLX509.java
- src/java/com/wolfssl/provider/jsse/WolfSSLX509X.java
Starting with wolfSSL 5.3.0 (https://github.com/wolfSSL/wolfssl/commit/afca455cda81f1b03998b24a369373f2d6531c69), the `wolfSSL_get_peer_certificate()` API returns a new/duplicate `WOLFSSL_X509` structure that needs to be explicitly freed with `wolfSSL_X509_free()`.
Prior to wolfSSL 5.3.0, `wolfSSL_get_peer_certificate()` returned a pointer to internal memory that was freed automatically by normal native wolfSSL cleanup routines.
This shows up through some exploration with `-fsanitize=address`:
```
Indirect leak of 10 byte(s) in 1 object(s) allocated from:
#0 0x7f5b9d305808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
#1 0x7f5a404785af in wolfSSL_Malloc wolfcrypt/src/memory.c:352
#2 0x7f5a405296b0 in CopyDecodedToX509 src/internal.c:12942
#3 …
```
> Free WOLFSSL_X509 from wolfSSL_get_peer_certificate() with wolfSSL >= 5.3.0

- .github/workflows/infer.yml
- .github/workflows/main.yml
- scripts/infer.sh
- src/java/com/wolfssl/provider/jsse/WolfSSLEngineHelper.java
This PR adds GitHub actions logic to run Facebook Infer on all pull requests.
This also fixes one Infer warning that showed up on Linux.
> Run Facebook Infer on PRs with GitHub Actions

- native/com_wolfssl_WolfSSLSession.c
- src/java/com/wolfssl/WolfSSLSession.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngineHelper.java
- src/java/com/wolfssl/provider/jsse/WolfSSLInternalVerifyCb.java
- src/java/com/wolfssl/provider/jsse/WolfSSLServerSocket.java
- src/java/com/wolfssl/provider/jsse/WolfSSLSocket.java
This PR tries to do some optimization for better garbage collection, based on testing with VisuaVM.
- Close `WolfSSLInputStream/WolfSSLOutputStream` when `SSLSocket.close()` is called. This releases the internal references to `WolfSSLSession` and `WolfSSLSocket` to allow easier garbage collection of these Input/OutputStream objects.
- Release/reset `WolfSSLEngineHelper` state when `WolfSSLSocket.close()` is called, removing internal object references and allowing easier garbage collection.
- Set `clientSNIRequested` and `ctx` to null inside `WolfSSLSession` when `freeSSL()` is called, potentially reducing the size of `WolfSSLSession` objects in memory until they are garbage collected.
- Remove finalizer method from `WolfSSLInternalVerifyCb` class. This is not needed and slows down garbage …
> Optimization pass for better garbage collection

- .github/workflows/main.yml
- native/com_wolfssl_WolfSSLSession.c
- native/com_wolfssl_WolfSSLSession.h
- src/java/com/wolfssl/WolfSSLSession.java
- src/java/com/wolfssl/provider/jsse/WolfSSLSocket.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLSocketTest.java
- src/test/com/wolfssl/test/WolfSSLSessionTest.java
This PR wraps the native wolfSSL API: `wolfSSL_SessionIsSetup(WOLFSSL_SESSION* session);` in the static Java method `WolfSSLSession.sessionIsSetup(long session)`.
The native session pointer can be obtained from a calling Java application by calling `WolfSSLSession.getSession()`.  `WolfSSLSession.getSession()` behaves like `wolfSSL_get1_session()` and returns a duplicate/copy of the `WOLFSSL_SESSION`. Calling applications must take care to free the session pointer when done by calling `WolfSSLSession.freeSession(long session)`.
Native `wolfSSL_SessionIsSetup()` was added after wolfSSL 5.7.0 with https://github.com/wolfSSL/wolfssl/pull/7430. If using native wolfSSL `LIBWOLFSSL_VERSION_HEX` in `wolfssl/version.h` is not greater than `0x05007000`, then `WOLFSSL_PR7430_PATCH_APPLIED` must be …
> JNI: wrap wolfSSL_SessionIsSetup() in WolfSSLSession

- examples/MyTls13SecretCallback.java
This PR corrects the example TLS 1.3 secret callback (`examples/MyTls13SecretCallback.java`) strings for `CLIENT_TRAFFIC_SECRET` and `SERVER_TRAFFIC_SECRET` to include the `_0`.
This example and support were originally added with https://github.com/wolfSSL/wolfssljni/pull/181.
ZD 17211
> Correct example TLS 1.3 secret callback

- src/java/com/wolfssl/provider/jsse/WolfSSLSocket.java
Calling the read() method (with no parameters) on a WolfSSLInputStream will now reflect the end of a stream in the return value. If the end of the stream has been reached, -1 should be returned instead of a byte (as noted here: https://docs.oracle.com/javase/8/docs/api/java/io/InputStream.html#read-- ).
> fix read() in WolfSSLInputStream to reflect end of stream

- native/com_wolfssl_WolfSSLSession.c
- native/com_wolfssl_WolfSSLSession.h
- src/java/com/wolfssl/WolfSSLSession.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngine.java
- src/java/com/wolfssl/provider/jsse/WolfSSLImplementSSLSession.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLSocketTest.java
This PR includes the following fixes to `SSLEngine`:
- Only save the client session (`WOLFSSL_SESSION`) to the cache if the handshake has finished successfully and there is no outstanding error from `wolfSSL_get_error() / getError()`.  This may prevent subsequent session resumption attempts trying to load/use a session that was in an error state.
- Synchronize calls to `wolfSSL_get_error() / getError()` with `ioLock` in case `WOLFSSL` state is changing. We want to prevent getting an error until activity is done/paused on the session.
This PR also fixes some issues found while testing wolfJSSE against the SunJSSE `SSLEngine` tests, including:
- Correctly return `SSL_SUCCESS` from `WolfSSLEngine.ClosingConnection()` when `ZERO_RETURN` is received
- Correctly return …
> SSLEngine fixes for session cache, getError(), and unwrap() HandshakeStatus

- src/java/com/wolfssl/provider/jsse/WolfSSLKeyManager.java
- src/java/com/wolfssl/provider/jsse/WolfSSLTrustManager.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLTrustX509Test.java
Both KeyManagerFactory and TrustManagerFactory will throw IllegalStateExceptions if they are used without being initialized. This includes calling getKeyManagers() on an uninitialized KeyManagerFactory and calling getTrustManagers() on an uninitialized TrustManagerFactory. The updated behavior aligns with what is described in the javadocs:
https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/TrustManagerFactory.html#getTrustManagers--
https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/KeyManagerFactory.html#getKeyManagers--
> KeyManagerFactory and TrustManagerFactory throw exceptions if used when uninitialized

- native/com_wolfssl_WolfSSL.h
- native/com_wolfssl_WolfSSLSession.c
- native/com_wolfssl_WolfSSLSession.h
- src/java/com/wolfssl/WolfSSL.java
- src/java/com/wolfssl/WolfSSLSession.java
- src/java/com/wolfssl/provider/jsse/WolfSSLAuthStore.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngine.java
- src/java/com/wolfssl/provider/jsse/WolfSSLImplementSSLSession.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLEngineTest.java
This PR includes a few various fixes for `SSLEngine` including:
- Only set `HandshakeStatus.FINISHED` for session tickets being received **after** the handshake has completed. Otherwise this may put callers into an odd state when the handshake has not finished yet.
- Calling `beginHandshake()` more than once can be done to instigate renegotiation. Since wolfJSSE SSLEngine implementation does not support renegotiation yet, we throw a `SSLException` to make it clear to callers that is the case. This matches behavior of some other providers that do not support renegotiation.
- Correctly mark inbound and outbound `closed` when we receive fatal alerts on the client or server sides. This fix was made after running the SunJSSE `EngineCloseOnAlert` test against wolfJSSE.
This PR includes one …
> SSLEngine fixes around HandshakeStatus, beginHandshake(), and alerts

- src/test/com/wolfssl/provider/jsse/test/WolfSSLSocketTest.java
Edit the TLS 1.0 and TLS 1.1 connection tests so that they will run if TLS1.0 and TLS1.1 have been compiled into the native wolfSSL library. The disabledAlgorithms Security property should be reset when testing these protocols because they are typically disabled by default and in that case the tests would fail.
> update TLSv1.0 and TLSv1.1 test

- src/java/com/wolfssl/provider/jsse/WolfSSLImplementSSLSession.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLSessionTest.java
This PR adjusts `SSLSession.getPeerCertificates()` to return an array of type`X509Certificate` rather than `Certificate`. Previously wolfJSSE created individual array elements as `java.security.cert.X509Certificate` objects, but returned them as a `java.security.cert.Certificate[]` to conform to the Javadoc specification for `SSLSession.getPeerCertificates()`:
```
Certificate[] getPeerCertificates() throws SSLPeerUnverifiedException
```
Some callers of this API (for example Postgres) tries to cast this return back to an array of `X509Certificate[]`, such as:
```
SSLSession session;
X509Certificate[] peerCerts;
...
peerCerts = (X509Certificate[]) session.getPeerCertificates();
```
This cast will throw an Exception similar to:
```
java.lang.ClassCastException: class …
```
> Return X509Certificate[] from SSLSession.getPeerCertificates()

- src/java/com/wolfssl/provider/jsse/WolfSSLServerSocket.java
The close() method currently causes some synchronization issues. The close() method just calls super.close() which is called anyways so deleting will just prevent those synchronization issues.
> Delete close method in WolfSSLServerSocket

- src/java/com/wolfssl/provider/jsse/WolfSSLEngine.java
Adjust a small typo in the debugging logs to increase debugging accuracy.
> Fix mistake in SSLEngine debug logs

- src/java/com/wolfssl/provider/jsse/WolfSSLImplementSSLSession.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLSessionTest.java
Fixed getLocalPrincipal to changed principal from null, before it would never change with the for loop and we can assume that the user cert is the first in the cert chain.
> Changed getLocalPrincipal to assume user cert is first in chain

- src/java/com/wolfssl/provider/jsse/WolfSSLSocket.java
The following changes help wolfJSSE align more closely with standards outlined in the javadocs:
- Ensure that if the implicit handshake in SSLSocket.getSession() fails, the socket is closed
- If the handshake fails in getSession(), return an invalid SSLSession object with the invalid cipher suite "SSL_NULL_WITH_NULL_NULL"
- If any handshake is unsuccessful, close the socket before throwing an exception
https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/SSLSocket.html
> Close socket if handshake fails

- README.md
- native/com_wolfssl_WolfSSL.h
- native/com_wolfssl_WolfSSLSession.c
- src/java/com/wolfssl/WolfSSL.java
- src/java/com/wolfssl/WolfSSLSession.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngine.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngineHelper.java
- src/java/com/wolfssl/provider/jsse/WolfSSLSocket.java
**Addition of `poll()` Support:**
This PR adds support for using `poll()` by default instead of `select()` on native file descriptors.  The previous `select()` behavior was left in tact and used as a default for Windows builds still. `select()` can also be used by building the native JNI library with `WOLFJNI_USE_IO_SELECT` defined. See `java.sh` `cflags` section for where that could be added.
We do not monitor lots of file descriptors at once ourselves inside wolfSSL JNI/JSSE, but one disadvantage to using `select()` is that for file descriptor numbers larger than `FD_SETSIZE`, the `FD_ISSET` and related macros result in undefined behavior. `FD_SETSIZE` defaults to `1024` on most systems, so is not very scalable for consumers using wolfSSL JNI/JSSE in processes that are opening and using …
> JNI/JSSE: Add support for poll(), fix for EAGAIN and select()

- README.md
- examples/provider/ClientJSSE.java
- examples/provider/ServerJSSE.java
- examples/provider/convert-to-wks.sh
- src/java/com/wolfssl/provider/jsse/WolfSSLKeyManager.java
- src/java/com/wolfssl/provider/jsse/WolfSSLTrustManager.java
- src/java/com/wolfssl/provider/jsse/WolfSSLUtil.java
This PR adds support for using wolfJCE's `WKS` KeyStore type, which is in review on wolfcrypt-jni here (https://github.com/wolfSSL/wolfcrypt-jni/pull/67).  Specifically this PR:
- Gives preference to try and load `WKS` KeyStore type first before falling back to try and load others (BKS, JKS, etc).
- When auto-loading the system CA/root certificates (ex: jssecacerts, cacerts), wolfJSSE first tries to find and load a WKS equivalent file at the same location (ex: jssecacerts.wks, cacerts.wks)
- New Security property added (`wolfjsse.keystore.type.required`) which can be used to restrict use of KeyStore type to the one set in this property. This can be used for example to help conform to wolfCrypt FIPS 140-2/3 crypto usage by setting to "WKS" when wolfJCE is also used and installed on the …
> Add wolfJCE WKS KeyStore Support

- native/com_wolfssl_WolfSSLSession.c
- native/com_wolfssl_WolfSSLSession.h
- src/java/com/wolfssl/WolfSSLSession.java
- src/test/com/wolfssl/test/WolfSSLSessionTest.java
This PR wraps the native `wolfSSL_SESSION_dup()` API in `WolfSSLSession.duplicateSession()`. This can be used to create a duplicate copy of a native `WOLFSSL_SESSION` pointer.
> JNI: wrap native wolfSSL_SESSION_dup() in WolfSSLSession.duplicateSession()

- src/java/com/wolfssl/provider/jsse/WolfSSLInternalVerifyCb.java
- src/java/com/wolfssl/provider/jsse/WolfSSLTrustX509.java
There were a few places in the internal peer verification logic where if a lower-level exception was thrown, the exception message was disregarded. This PR passes those lower level exception messages up, to help with debugging and log analysis.
> JSSE: pass lower level exception messages up during X509TrustManager peer verification

- src/java/com/wolfssl/provider/jsse/WolfSSLEngine.java
close inbound if ssl.getError(ret) == UNKNOWN_ALPN_PROTOCOL_NAME_E
> close inbound on UNKNOWN_ALPN_PROTOCOL_NAME_E

- native/com_wolfssl_WolfSSLSession.c
Java_com_wolfssl_WolfSSLSession_read() returns error value of socketPoll() if encountered. Originally breaks and  returns size.
> read returns error value to timeout

- src/java/com/wolfssl/provider/jsse/WolfSSLParameters.java
- src/java/com/wolfssl/provider/jsse/WolfSSLServerSocket.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLServerSocketTest.java
- Add `getSSLParameters()` method to WolfSSLServerSocket class, this way SSLParameters returned will be accurate to the SSLServerSocket (method is exactly the same as the corresponding WolfSSLSocket method)
- Add unit test for `getSSLParameters()` to WolfSSLServerSocketTest (very similar to the unit test for getSSLParameters in WolfSSLSocketTest)
- Update `copy()` method in WolfSSLParameters to include all variables. This way, Sockets created with a ServerSocket will have matching SSLParameters
> Fixes to SSLParameters and WolfSSLServerSocket

- examples/README.md
- examples/SimpleThreadedClient.java
- examples/SimpleThreadedClient.sh
- examples/SimpleThreadedServer.java
- examples/SimpleThreadedServer.sh
This PR adds two new JNI-level (not JSSE) examples, a threaded client and server example. The client does session resumption when possible and maintains an application-wide client session cache to hold native `WOLFSSL_SESSION` pointers.
- `examples/SimpleThreadedClient.java` - makes concurrent client connections to a server located at `localhost:11111`. Default number of client threads is **5**, but can be changed using the `-n <num_connections>` command line argument. This example implements a simple application-wide Java client cache where native `WOLFSSL_SESSION` pointers are stored and used for session resumption where possible. See code comments for further explanation.
- `examples/SimpleThreadedServer.java` - starts at `localhost:11111` and waits for client connections. When a …
> JNI: add example threaded client/server applications (JNI only)

- native/com_wolfssl_WolfSSLSession.c
- native/com_wolfssl_WolfSSLSession.h
- src/java/com/wolfssl/WolfSSLSession.java
- src/java/com/wolfssl/provider/jsse/WolfSSLAuthStore.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngineHelper.java
- src/java/com/wolfssl/provider/jsse/WolfSSLImplementSSLSession.java
This PR adjusts client-side session resumption to verify the original cipher suite and protocol used for the original session are enabled.
If an initial connection to a server is established and saved into the session cache, but the application then adjusts or removes cipher suites with `SSLSocket/SSLEngine.setEnabledCipherSuites()` or `SSLSocket/SSLEngine.setEnabledProtocols()`, if the cipher suite or protocol used in the first connection is no longer enabled we should fall back to full handshake for the second connection.
> JSSE: Session resumption check for enabled cipher suite and protocol

- src/java/com/wolfssl/provider/jsse/WolfSSLEngine.java
Update the TLS protocol used in the SSLSession after the handshake is complete. Currently, the TLS protocol is not being updated for SSLEngine and calling getProtocol() returns "NONE" after the handshake.
> Store protocol after handshake in SSLSession

- native/com_wolfssl_WolfSSL.h
- src/java/com/wolfssl/WolfSSL.java
- src/java/com/wolfssl/provider/jsse/WolfSSLSocket.java
This PR adjusts `WolfSSLInputStream.read()` to return `-1` when native `wolfSSL_read()` returns `SOCKET_ERROR_E / -308`. Returning `-1` indicates end of stream to caller.
Potential fix for customer issue.
> JSSE: return end of stream in WolfSSLInputStream.read() on SOCKET_ERROR_E

- src/java/com/wolfssl/WolfSSLX509Name.java
- src/java/com/wolfssl/provider/jsse/WolfSSLContext.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngineHelper.java
- src/java/com/wolfssl/provider/jsse/WolfSSLImplementSSLSession.java
- src/java/com/wolfssl/provider/jsse/WolfSSLServerSocket.java
- src/java/com/wolfssl/provider/jsse/WolfSSLTrustManager.java
This PR includes some cleanup items found by a run of SpotBugs on the codebase.
> JSSE: fixes for some items found with SpotBugs

- src/java/com/wolfssl/WolfSSL.java
- src/java/com/wolfssl/provider/jsse/WolfSSLSocket.java
This PR fixes a potential deadlock that could occur when `WolfSSLSocket.close()` and `WolfSSLInput/OutputStream.close()` are called simultaneously by different threads.
> Fix potential deadlock on close() between SSLSocket and Input/OutputStream

- README.md
- src/java/com/wolfssl/provider/jsse/WolfSSLDebug.java
This PR adds a new System property (`wolfjsse.debugFormat`) which can be set to `JSON` to output all debug log messages in JSON format.  This can be helpful when logs need to be fed into tools such as DataDog.
To enable, set the System property at runtime or on the command line:
```
System.setProperty("wolfjsse.debug", "true");
System.setProperty("wolfjsse.debugFormat", "JSON");
```
```
-Dwolfjsse.debug=true -Dwolfjsse.debugFormat=JSON
```
This will cause all log messages to be output in a JSON format like so:
```
{
"@timestamp": "2024-04-05 11:13:07.193",
"level": "INFO",
"logger_name": "wolfJSSE",
"message": "[ WolfSSLTrustManager] entered engineInit()",
"thread_name": "main",:
"thread_id": "1"
}
```
> Add option to print debug logs in JSON format

- src/java/com/wolfssl/WolfSSLCertificate.java
- src/java/com/wolfssl/provider/jsse/WolfSSLDebug.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngineHelper.java
- src/java/com/wolfssl/provider/jsse/WolfSSLImplementSSLSession.java
- src/java/com/wolfssl/provider/jsse/WolfSSLSessionContext.java
- src/java/com/wolfssl/provider/jsse/WolfSSLUtil.java
This PR cleans up `ant` build warnings on Corretto 20.0.1.
> JNI/JSSE: clean up ant build warnings for Corretto 20.0.1

- README.md
- src/java/com/wolfssl/provider/jsse/WolfSSLEngineHelper.java
- src/java/com/wolfssl/provider/jsse/WolfSSLUtil.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLEngineTest.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLSessionContextTest.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLSocketTest.java
This PR adds support for a new Java Security property which can be used to disable the Java client-side session cache. If this property is set to "true", it prevents wolfJSSE from storing sessions into the Java client session cache:
**java.security**:
```
wolfjsse.clientSessionCache.disabled=true
```
**Programmatically**:
```
Security.setProperty("wolfjsse.clientSessionCache.disabled", "true");
```
README.md has been updated with a note about this new property. JUnit test has been added to test that resumption is not done when set.
> JSSE: add Security property to disable Java client session cache

- src/java/com/wolfssl/provider/jsse/WolfSSLSocket.java
A previous PR (https://github.com/wolfSSL/wolfssljni/pull/222) had introduced an internal helper method (`checkAndInitSSLSocket()`) to help make sure the SSLSocket was initialized and native file descriptor set.  This PR makes two small fixes:
- Corrects the expected exception thrown from `getInputStream()` and `getOutputStream()` from `IOException` to `SocketException`.
- Adds an independent flag indicating if the native fd has been set or not. This allows code to initialize the cert/key, and later come back and set the file descriptor once the socket is connected.
This PR fixes our nightly Jenkins SunJSSE test.
> JSSE: correct SSLSocket exception types, fix for setting fd

- src/java/com/wolfssl/provider/jsse/WolfSSLSocket.java
This PR fixes a few deadlock issues that could occur between SSLSocket.close() and the associated SSLSocket's OutputStream.write().
Originally from user report of deadlock, was similar to:
```
Thread 1:
at com.wolfssl.provider.jsse.WolfSSLSocket$WolfSSLOutputStream.close(WolfSSLSocket.java:2618)
- waiting to lock <0x00000000f42874f8> (a com.wolfssl.provider.jsse.WolfSSLSocket$WolfSSLOutputStream)
at com.wolfssl.provider.jsse.WolfSSLSocket.close(WolfSSLSocket.java:1951)
- locked <0x00000000f4287588> (a java.lang.Object)
- locked <0x00000000f4287578> (a java.lang.Object)
- locked <0x00000000f4287518> (a com.wolfssl.provider.jsse.WolfSSLSocket)
Thread 2:
at com.wolfssl.provider.jsse.WolfSSLSocket$WolfSSLOutputStream.write(WolfSSLSocket.java:2684)
- waiting to lock <0x00000000f4287588> (a …
```
> JSSE: fix deadlock issues between SSLSocket close() and OutputStream write()

- examples/provider/rmi/README.md
- examples/provider/rmi/RmiClient.java
- examples/provider/rmi/RmiClient.sh
- examples/provider/rmi/RmiRemoteInterface.java
- examples/provider/rmi/RmiServer.java
- examples/provider/rmi/RmiServer.sh
- examples/provider/rmi/RmiTLSClientSocketFactory.java
- examples/provider/rmi/RmiTLSServerSocketFactory.java
This PR adds an example RMI client and server that work over TLS, located in the `examples/provider/rmi` directory. Examples are compiled when `ant examples` is run:
```
$ ./java.sh
$ ant
$ ant examples
```
Then, the client and server can be run from the `wolfssljni` root:
```
./examples/provider/rmi/RmiServer.sh
./examples/provider/rmi/RmiClient.sh
```
`examples/provider/rmi/RmiServer.java` - RMI server (implements RmiRemoteInterface)
`examples/provider/rmi/RmiClient.java` - RMI client
`examples/provider/rmi/RmiRemoteInterface.java` - RMI remote object interface
`examples/provider/rmi/RmiTLSClientSocketFactory.java` - client TLS socket factory for RMI
`examples/provider/rmi/RmiTLSServerSocketFactory.java` - server TLS socket factory for RMI
Expected output should be:
```
$ …
```
> JSSE: add basic RMI example client and server

- ChangeLog.md
- IDE/WIN/README.md
- README.md
- build.xml
- native/com_wolfssl_WolfSSLSession.c
- pom.xml
- src/java/com/wolfssl/provider/jsse/WolfSSLProvider.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLTrustX509Test.java
This PR includes prep work for the wolfSSL JNI/JSSE 1.14 release:
- Fixes use of `select()` on Windows, since `poll()` is not available
- Small fix for `WolfSSLTrustX509Test` to not run RSA-PSS TLS 1.3 test if TLS 1.3 is disabled
- Update README for Windows builds
- Update version to 1.14
- Update ChangeLog with release notes
Tested against release cycle items, including:
- wolfSSL master, 5.7.4, FIPSv2, FIPSv5, FIPS Ready
- Java 8, 11, 17, 20, 22, 23
- Facebook Infer (Mac)
- Android Studio IDE project
- Alongside wolfJCE installed in system
- Windows Visual Studio build
> Prep for 1.14 Release

- src/java/com/wolfssl/WolfSSLDebug.java
- src/java/com/wolfssl/provider/jsse/WolfSSLAuthStore.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngine.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngineHelper.java
- src/java/com/wolfssl/provider/jsse/WolfSSLImplementSSLSession.java
- src/java/com/wolfssl/provider/jsse/WolfSSLSocket.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLSessionTest.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLSocketTest.java
- src/test/com/wolfssl/test/WolfSSLSessionTest.java
This PR includes fixes to `WolfSSLSocket`, `WolfSSLImplementSSLSession`, and related classes:
- Removes setting `this.ssl` and `this.socket` to `null` in `SSLSocket` `Input/OutputStream.close()` methods, in case there is another thread blocked on `select/poll()` in `Input/OutputStream.read/write()`. Otherwise, this could result in a `NullPointerException`.
- Adds JUnit tests to test getting the SSLSession (`SSLSocket.getSession()`) at various times throughout handshake process (before, after) and calling SSLSession methods. This will help prevent NullPointerExceptions in the future.  Fixes are included to `WolfSSLSocket` based on the results of this test.
> JSSE: adjust variable resets in Input/OutputStream.close(), more SSLSession tests and fixes

- .github/workflows/main.yml
- native/com_wolfssl_WolfSSLSession.c
- src/java/com/wolfssl/WolfSSLSession.java
Java callers of `WolfSSLSession.getSession()` should always expect to free the returned session pointer with `WolfSSLSession.freeSession(long session)`.  Previously `getSession()` called `wolfSSL_SESSION_dup()` but only for connections that were not TLS 1.3 or had a session ticket.  Calling `wolfSSL_get1_session()` should be a more consistent solution since it increases the ref count on the WOLFSSL_SESSION in question.
This should make it more interoperable with various build options - TLS 1.3, without TLS 1.3, with `-DNO_SESSION_CACHE_REF`.
This also adds one GitHub Action test for the wolfSSL configure `--enable-jni CFLAGS=-DNO_SESSION_CACHE_REF`.
Potential fix for ZD 17211.
> Always call wolfSSL_get1_session() inside native JNI WolfSSLSession.getSession()

- src/java/com/wolfssl/provider/jsse/WolfSSLImplementSSLSession.java
Adds ability for getRequestedServerNames() to return SNI request saved by server side. Previously only returned SNI server name if called on client side.
> Return cached SNI request from Server side

- src/java/com/wolfssl/WolfSSLSession.java
- src/java/com/wolfssl/provider/jsse/WolfSSLImplementSSLSession.java
Adds `getSNIRequestBytes()` method to return the SNI name byte array of the session. Modify `getSNIRequest(`) to call `getSNIRequestBytes()` and return the value as a String using UTF-8 encoding. Previously, returned `reqBytes.toString()` which was the String representation of the `reqBytes` Object.
> Add getSNIRequestBytes() and modify return value of getSNIRequest()

- src/java/com/wolfssl/provider/jsse/WolfSSLEngine.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngineHelper.java
- src/java/com/wolfssl/provider/jsse/WolfSSLServerSocket.java
- src/java/com/wolfssl/provider/jsse/WolfSSLSocket.java
Added exception handling for `WolfSSLException`, implementing key size checks for Diffie-Hellman (DH) key exchanges, and updating method signatures to reflect the new exception types.
Tested running the testOSX.sh to make sure there were no tests regression after the changes.
> Added check for legacy DHE keys (for cipher suites using keys less than 1024 bits)

- native/com_wolfssl_WolfSSL.c
This PR adjusts native JNI code that runs FIPS CASTs to call `wc_RunAllCast_fips()` when available. It also define-protects per-algorithm CAST functions.
> JNI/JSSE: call wc_RunAllCast_fips() for FIPS builds when available

- native/com_wolfssl_WolfSSLSession.c
- native/com_wolfssl_WolfSSLSession.h
- src/java/com/wolfssl/WolfSSLSession.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngine.java
This is an optimization PR that removes an extra `byte[]` array creation inside `WolfSSLEngine.RecvAppData()`, which is called from `SSLEngine.unwrap()`.
Prior to this PR, we allocated a new `byte[]` to read ByteBuffer data into and pass down to JNI for `SSL_read()` operations.
This PR changes that behavior so that if there is only one `ByteBuffer` in the output `ByteBuffer[]` passed to `unwrap()`, that ByteBuffer is passed down to JNI directly where the underlying array is retrieved and used without an extra array creation.
This should have positive impacts on reducing the number of objects created, especially in use cases where lots of data is being received (or downloaded) via an `SSLEngine.unwrap()` interface.
> JNI/JSSE: optimize out array creation in WolfSSLEngine RecvAppData()

- native/com_wolfssl_WolfSSLSession.c
Fix of improper handling of DirectByteBuffers in the JNI layer. Previously, the native read() method would throw an exception when encountering a DirectByteBuffer, breaking the optimization path for single-buffer reads in WolfSSLEngine.
This change modifies the JNI implementation to properly handle both array-backed and direct ByteBuffers, maintaining the performance benefits of both buffer types while fixing the test failure.
- Added support for DirectByteBuffers using GetDirectBufferAddress
- Preserved existing optimization path for array-backed buffers
- Maintained proper position updates and error handling for both types
- Fixed SSLEngine/Arrays test without compromising performance
> fix: handle DirectByteBuffers in WolfSSLSession.read()

- .github/workflows/linux-common.yml
- .github/workflows/main.yml
- README.md
- java.sh
- native/com_wolfssl_WolfSSLSession.c
- native/com_wolfssl_WolfSSLSession.h
- src/java/com/wolfssl/WolfSSLSession.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngine.java
- src/java/com/wolfssl/provider/jsse/WolfSSLSocket.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLSocketTest.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLTestFactory.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLTrustX509Test.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLX509Test.java
This PR adjusts JSSE and lower-level JNI behavior around `SSLSocket.close()`. When `close()` is called, it should interrupt any other threads blocked in `select()/poll()` from `read()/write()` operations.
This adds a `pipe()` descriptor which is watched by `select()/poll()`. That pipe is written to by a thread calling `SSLSocket.close()` to wake those blocked threads up - preventing a possible deadlock in this scenario.
This `pipe()` solution is currently only implemented for **non-Windows platforms** in this PR.
Should fix SunJSSE test: `SSLSocketImpl/BlockedAsyncClose.java`.
Minor fixes also included in this PR:
- Add ability to pass `CFLAGS` to `java.sh`, ie: `CFLAGS="-DTEST_DEFINE" ./java.sh`
- Add GitHub Action test for testing with `-DWOLFJNI_USE_IO_SELECT` defined (uses `select()` …
> JSSE: calling SSLSocket.close() should interrupt threads blocked in select()/poll()

- ChangeLog.md
- IDE/Android/.idea/misc.xml
- IDE/Android/README.md
- IDE/Android/app/src/main/cpp/CMakeLists.txt
- IDE/Android/app/src/main/java/com/example/wolfssl/MainActivity.java
- README.md
- build.xml
- pom.xml
- scripts/infer.sh
- src/java/com/wolfssl/WolfSSLCertRequest.java
- src/java/com/wolfssl/WolfSSLCertificate.java
- src/java/com/wolfssl/WolfSSLSession.java
- src/java/com/wolfssl/provider/jsse/WolfSSLProvider.java
This PR includes prep work for the wolfSSL JNI/JSSE 1.15 release:
- Update version to 1.15
- Fix Facebook Infer script exit code (was not running properly)
- Fix Facebook Infer reports for thread safety / potential deadlock issues
- Update example Android app CMakeLists.txt for latest FIPS Ready compatibility
- Update ChangeLog with release notes
Tested against release cycle items, including:
- wolfSSL master, 5.7.6, FIPSv2, FIPSv5, FIPSv6, FIPS Ready
- Java 8, 11, 17, 21, 23
- Facebook Infer (Mac)
- Android Studio IDE project (normal and FIPS Ready)
- Windows Visual Studio build
> Prep for 1.15 Release

- README.md
- src/java/com/wolfssl/provider/jsse/WolfSSLEngineHelper.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLSocketTest.java
Introduce wolfjsse.autoSNI property to make SNI behavior configurable. When
set to true, enables legacy automatic SNI based on hostname/peer. By default,
SNI is only set through explicit SSLParameters configuration.
- Fixes SSLSocketExplorerWithSrvSNI test failures
- Maintains compatibility for existing applications
- Adds test coverage in WolfSSLSocketTest
> Add wolfjsse.autoSNI Security property

- src/java/com/wolfssl/provider/jsse/WolfSSLEngineHelper.java
Enable SNI automatically when detecting HttpsURLConnection's unique initialization pattern, fixing ImpactOnSNI test while preserving default SNI behavior for SSL sockets.
> wolfjsse: auto-enable SNI for HttpsURLConnection

- README.md
- examples/Client.java
- examples/Server.java
- native/com_wolfssl_WolfSSL.c
- native/com_wolfssl_WolfSSL.h
- native/com_wolfssl_WolfSSLSession.c
- native/com_wolfssl_WolfSSLSession.h
- scripts/infer.sh
- src/java/com/wolfssl/WolfSSL.java
- src/java/com/wolfssl/WolfSSLSession.java
- src/java/com/wolfssl/WolfSSLSessionTicketCallback.java
- src/java/com/wolfssl/provider/jsse/WolfSSLContext.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngine.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngineHelper.java
- src/java/com/wolfssl/provider/jsse/WolfSSLParameters.java
- src/java/com/wolfssl/provider/jsse/WolfSSLParametersHelper.java
- src/java/com/wolfssl/provider/jsse/WolfSSLProvider.java
- src/java/com/wolfssl/provider/jsse/WolfSSLServerSocket.java
- src/java/com/wolfssl/provider/jsse/WolfSSLUtil.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLContextTest.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLEngineTest.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLSocketTest.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLTestFactory.java
- src/test/com/wolfssl/test/WolfSSLTest.java
This PR adds DTLS 1.3 support to the wolfJSSE `SSLContext` class, for use through the `SSLEngine` interface. SunJSSE supports up to DTLS 1.2 through the SSLEngine interface, so we are matching similar behavior here for DTLS 1.3.
To support this addition, this PR also makes the following changes:
- Adds DTLS 1.3 to the thin JNI-only layer
- Wraps `wolfSSL_DisableExtendedMasterSecret()`
- Adds support for the Java system property: `jdk.tls.useExtendedMasterSecret` for enabling or disabling the TLS Extended Master Secret (EMS) extension. Enabled by default unless explicitly disabled.
- Wraps `wolfSSL_send_hrr_cookie()` in `WolfSSLSession.sendHrrCookie()` for enabling HelloRetryRequest use in SSLEngine DTLS support.
- Wraps `wolfSSL_dtls_get_drop_stats()` for use in SSLEngine DTLS detection …
> Add support for DTLS 1.3 (`DTLSv1.3`) through `SSLContext` / `SSLEngine`

- src/java/com/wolfssl/provider/jsse/WolfSSLAuthStore.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngine.java
- src/java/com/wolfssl/provider/jsse/WolfSSLImplementSSLSession.java
- Fixes the test SSLSession/ResumeTLS13WithSNI.java (SunJSSE);
- Adds SNI storing (and restoring) at the wolfJSSE level on session resumption for TLS 1.3;
Note: Requires `-DWOLFSSL_TLS13_MIDDLEBOX_COMPAT` to be enabled.
> Fix TLS 1.3 session resumption to preserve SNI extension

- native/com_wolfssl_WolfSSL.c
- native/com_wolfssl_WolfSSLContext.c
- native/com_wolfssl_WolfSSLSession.c
- native/com_wolfssl_WolfSSLSession.h
- native/com_wolfssl_globals.h
- scripts/infer.sh
- src/java/com/wolfssl/WolfSSL.java
- src/java/com/wolfssl/WolfSSLByteBufferIORecvCallback.java
- src/java/com/wolfssl/WolfSSLByteBufferIOSendCallback.java
- src/java/com/wolfssl/WolfSSLSession.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngine.java
- src/java/com/wolfssl/provider/jsse/WolfSSLImplementSSLSession.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLEngineTest.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLSocketTest.java
- src/test/com/wolfssl/test/WolfSSLContextTest.java
- src/test/com/wolfssl/test/WolfSSLSessionTest.java
This PR contains work done to increase `SSLEngine` (`WolfSSLEngine`) performance, including:
- Use a single static direct ByteBuffer in `WolfSSLEngine.SendAppData()`, instead of allocating a new array each time the method is called.
- Use a static output array for I/O output callback instead of allocating a new one for each send.
- Cache `jmethodID` values once globally when library is initialized, instead of multiple time throughout execution of code paths.
- Add new helper functions to throw exceptions (`throwWolfSSLJNIException()`, `throwWolfSSLException()`), which causes `FindClass()` to only be called when we need to throw an exception, not every time some JNI functions are called.
- Add ByteBuffer-based wolfSSL I/O callback support, and plug them into `WolfSSLEngine`. This allows …
> SSLEngine Performance Optimizations

- native/com_wolfssl_WolfSSLSession.c
- src/test/com/wolfssl/test/WolfSSLContextTest.java
This PR makes a change to `com.wolfssl.WolfSSLSession` native JNI `NativeALPNSelectCb()` to ensure that the peer ALPN protocol list is null terminated before using `XSTRTOK()` to iterate over the list.
Caught with `-fsanitize=address` testing running existing JUnit tests:
```
[junit] =================================================================
[junit] ==12036==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000049e5b at pc 0x000150d1183c bp 0x70000a59f8a0 sp 0x70000a59f898
[junit] READ of size 1 at 0x602000049e5b thread T317
[junit]     #0 0x150d1183b in wc_strtok wc_port.c:1101
[junit]     #1 0x15035ac4c in NativeALPNSelectCb com_wolfssl_WolfSSLSession.c:5383
[junit]     #2 0x1510b199d in ALPN_Select tls.c:1858
[junit]     #3 0x151105e12 in DoTls13ClientHello …
```
> Null terminate `NativeALPNSelectCb()` peer protocol list before XSTRTOK

- src/java/com/wolfssl/WolfSSL.java
- src/java/com/wolfssl/WolfSSLCertManager.java
- src/java/com/wolfssl/WolfSSLCertRequest.java
- src/java/com/wolfssl/WolfSSLCertificate.java
- src/java/com/wolfssl/WolfSSLContext.java
- src/java/com/wolfssl/WolfSSLDebug.java
- src/java/com/wolfssl/WolfSSLSession.java
- src/java/com/wolfssl/WolfSSLX509Name.java
- src/java/com/wolfssl/WolfSSLX509StoreCtx.java
- src/java/com/wolfssl/provider/jsse/WolfSSLAuthStore.java
- src/java/com/wolfssl/provider/jsse/WolfSSLContext.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngine.java
- src/java/com/wolfssl/provider/jsse/WolfSSLEngineHelper.java
- src/java/com/wolfssl/provider/jsse/WolfSSLImplementSSLSession.java
- src/java/com/wolfssl/provider/jsse/WolfSSLInternalVerifyCb.java
- src/java/com/wolfssl/provider/jsse/WolfSSLKeyManager.java
- src/java/com/wolfssl/provider/jsse/WolfSSLKeyX509.java
- src/java/com/wolfssl/provider/jsse/WolfSSLProvider.java
- src/java/com/wolfssl/provider/jsse/WolfSSLServerSocket.java
- src/java/com/wolfssl/provider/jsse/WolfSSLServerSocketFactory.java
- src/java/com/wolfssl/provider/jsse/WolfSSLSocket.java
- src/java/com/wolfssl/provider/jsse/WolfSSLSocketFactory.java
- src/java/com/wolfssl/provider/jsse/WolfSSLTrustManager.java
- src/java/com/wolfssl/provider/jsse/WolfSSLTrustX509.java
- src/java/com/wolfssl/provider/jsse/WolfSSLUtil.java
- src/java/com/wolfssl/provider/jsse/WolfSSLX509.java
- src/java/com/wolfssl/provider/jsse/WolfSSLX509X.java
- src/test/com/wolfssl/test/WolfSSLSessionTest.java
This PR switches wolfssljni to use the Java Logging (`java.util.logging`) framework instead of using plain `System.out.println()` statements.
Using `System.out.println()` is not ideal for performance nor memory usage, since Strings are always allocated even if debug logging is disabled. Using Java Logging, and switching debug calls to use lambda style defers String allocation/creation until the debug log is actually used/printed.
Using `tls-channel` and benchmarking SSLEngine throughput when transferring large amounts of data, this is a performance optimization that builds upon https://github.com/wolfSSL/wolfssljni/pull/257.  With these debug changes, throughput performance is increased by an additional 26.8%.
> Switch to Java Logging (`java.util.logging`)

- native/com_wolfssl_WolfSSL.c
- native/com_wolfssl_WolfSSL.h
- src/java/com/wolfssl/WolfSSL.java
- src/java/com/wolfssl/WolfSSLCertRequest.java
- src/java/com/wolfssl/WolfSSLCertificate.java
This PR adjusts the `com.wolfssl.WolfSSL` class to dynamically get algorithm and key type ASN NID enum values (ex: RSAk, NID_surname, etc) instead of using hard-coded values. This is much more flexible in case these values change at the native level.
These hard coded values broke some unit tests after https://github.com/wolfSSL/wolfssl/commit/1e3718ea7b92b04d9d81dbf8e7d6032ca0a904cb was merged into native wolfSSL.
> Get ASN algorithm enum values dynamically in `WolfSSL.java`

- examples/provider/DtlsClientEngine.java
- examples/provider/DtlsClientEngine.sh
- examples/provider/DtlsServerEngine.java
- examples/provider/DtlsServerEngine.sh
- examples/provider/README.md
This PR adds a basic DTLS 1.3 client and server example which use the `SSLEngine` interface.  DTLS 1.3 was added to wolfssljni SSLEngine with this PR: https://github.com/wolfSSL/wolfssljni/pull/254.
The two new examples include:
- examples/provider/DtlsClientEngine.java
- examples/provider/DtlsServerEngine.java
Each has a corresponding bash script which should be used to run them:
- examples/provider/DtlsClientEngine.sh
- examples/provider/DtlsServerEngine.sh
Output should be similar to:
```
$ ./examples/provider/DtlsServerEngine.sh
DTLS 1.3 Server listening on port 11113
DTLS 1.3 Server Engine created
Waiting for client connection...
Client connected from /127.0.0.1:58703
DEBUG: Sent packet with 176 bytes
DEBUG: Received packet with 383 bytes
DEBUG: Sent packet with 176 bytes
DEBUG: Sent …
```
> JSSE examples: add DTLS 1.3 example client and server

- src/java/com/wolfssl/provider/jsse/WolfSSLEngineHelper.java
- src/java/com/wolfssl/provider/jsse/WolfSSLParameters.java
- src/java/com/wolfssl/provider/jsse/WolfSSLParametersHelper.java
- src/java/com/wolfssl/provider/jsse/WolfSSLSocket.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLSocketTest.java
Implements SNI matcher logic for server side wolfSSLSockets in wolfSSLEngineHelper's `doHandshake()`.
Adds functions 
- `setSNIMatchers()` - initialize or add to sniMatchers list.
- `getSNIMatchers()` - returns the sniMatchers or an empty list if sniMatchers is null or empty
- `matchSNI()` - compares requested SNI to sniMatchers list. Returns true if a match is found. Will ignore matching (return true) if sniMatchers or the requested server names are null or empty.
Passes SunJSSE tests: SSLSocketConsistentSNI.java, SSLSocketExplorer.java, SSLSocketExplorerFailure.java, SSLSocketExplorerMatchedSNI.java, SSLSocketExplorerWithCliSNI.java, SSLSocketExplorerWithSrvSNI.java, SSLSocketExplorerUnmatchedSNI.java.
Also added WolfSSLSocket test for matched and unmatched server names.
> implement SNI matcher logic

- .github/workflows/main.yml
- CLAUDE.md
- java.sh
- src/test/com/wolfssl/provider/jsse/test/WolfSSLEngineTest.java
This PR:
- Adds `-fPIC` to CFLAGS in `.java.sh` for Aarch64 hosts
- Adds a GitHub action that uses the `ubuntu-24.04-arm` runner so we get a test with Aarch64 and `--enable-armasm`
Aarch64 test runners are now available as of Jan 2025: https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/
> Use `-fPIC` on Aarch64, add GitHub Actions ARM with armasm test

- README.md
- native/com_wolfssl_WolfSSLSession.c
- native/com_wolfssl_WolfSSLSession.h
- src/java/com/wolfssl/WolfSSLSession.java
- src/java/com/wolfssl/provider/jsse/WolfSSLSocket.java
- src/test/com/wolfssl/test/WolfSSLSessionTest.java
This PR introduces a static per-thread pool of direct ByteBuffers to the `com.wolfssl.WolfSSLSession` class, to be used with `read()` and `write()` calls.
The main reason this is needed is to avoid unaligned memory access in the native JNI code, where previously we were doing pointer addition with the offset (ex: `buffer + offset`), which could result in unaligned memory use.  Using unaligned memory on some platforms (ex: Aarch64) can have performance impacts.  This was observed on a Raspberry Pi 5 (Aarch64) and a customer platform.
Each static buffer pool is per-thread.  Each direct ByteBuffer in the pool is 17k (BUFFER_SIZE), and the maximum pool size per thread is 16.  We will introduce Java Security properties which can be used to tune these values, which will be helpful to customize …
> Use static pool of direct ByteBuffers for WolfSSLSession read/write()

- src/java/com/wolfssl/provider/jsse/WolfSSLEngineHelper.java
- src/java/com/wolfssl/provider/jsse/WolfSSLParameters.java
This PR refactors `WolfSSLEngineHelper` to get and cache System and Security properties on class creation in the constructor, instead of getting them each time at runtime during handshake/etc operations.  This was changed here specifically for `setLocalServerNames()`, where potential thread contention may occur in the Security class when multiple threads concurrently try to get the values of these properties.
> JSSE: get System/Security properties on class initialization for WolfSSLEngineHelper

- README.md
- src/java/com/wolfssl/provider/jsse/WolfSSLImplementSSLSession.java
- src/java/com/wolfssl/provider/jsse/WolfSSLKeyManager.java
- src/java/com/wolfssl/provider/jsse/WolfSSLKeyX509.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLKeyX509Test.java
This PR modifies wolfJSSE's `X509ExtendedKeyManager` implementation (WolfSSLKeyX509.java) to cache entries from the provided KeyStore, instead of calling down to the KeyStore for each operation.
In heavily threaded environments, concurrent calls into WolfSSLKeyX509's methods which previously called down to the KeyStore directly could back up and cause large delays in some connections.  Some thread delays were observed to be 2-3 minutes in a heavily threaded application.
For backwards compatibility, this PR introduces a new Java Security property named `wolfjsse.X509KeyManager.disableCache` which can be set to "true" to disable caching and return to the previous behavior.
Additional JUnit tests have been added to test new cache functionality.
> JSSE: cache KeyStore entries in X509ExtendedKeyManager

- native/com_wolfssl_WolfSSLSession.c
- src/java/com/wolfssl/provider/jsse/WolfSSLSocket.java
This PR includes likely fixes for some use-after-free issues that have showed up when using `SSLSocket` in a multi threaded environment.  Typical use case is between multiple threads (for example in OkHttp) where one thread is doing TLS read operations while another thread manages connection state/closure. One possible crash sequence could be:
- Thread A calls a (SSLSocket) InputStream.read() operation
- Thread B simultaneously calls SSLSocket.close() - which tried to free the native WOLFSSL prior to this PR
- Thread B in the JNI freeSSL() call calls `XFREE(appData, NULL, DYNAMIC_TYPE_TMP_BUFFER);`
- Thread A attempts to access/use SSLAppData (ex: `appData->jniSessLock`)
This PR makes two changes:
- Before calling `freeSSL()` inside `WolfSSLSocket.close()`, check if the associated …
> Fixes to avoid use-after-free issues in WolfSSLSocket

- src/java/com/wolfssl/provider/jsse/WolfSSLSocket.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLSocketTest.java
This PR fixes a potential NullPointerException that could occur if `SSLSocket.close()` is called multiple times or concurrently from multiple threads.
This also adds a JUnit test to protect against regression.
> JSSE: fix for NullPointerException on double close() in WolfSSLSocket

- src/java/com/wolfssl/provider/jsse/WolfSSLX509.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLX509Test.java
This PR addresses https://github.com/wolfSSL/wolfssljni/issues/280, and implements the `toString()` method inside `WolfSSLPrincipal` (implements java.security.Principal).
Additional JUnit tests are added here to verify behavior correctness, as well as behavior of default `implies()` method implementation from `java.security.Principal`. Since this default behavior works for us, there is no need to re-implement in WolfSSLPrincipal.
> JSSE: implement WolfSSLPrincipal.toString() inside WolfSSLX509

- src/java/com/wolfssl/provider/jsse/WolfSSLSocket.java
- src/test/com/wolfssl/provider/jsse/test/WolfSSLSocketTest.java
This PR adds null pointer checking to `WolfSSLSocket`, specifically for the issue in `close()` where `this.EngineHelper.clearObjectState();` could have been called in some scenarios if `this.EngineHelper` had already been set to null.
A regression test has also been added as part of this PR.
> Check EngineHelper for null in SSLSocket.close()

- native/com_wolfssl_WolfSSLSession.c
- native/com_wolfssl_WolfSSLSession.h
- src/java/com/wolfssl/WolfSSLSession.java
- src/test/com/wolfssl/test/WolfSSLSessionTest.java
Adds wrapper and unit tests for get and set session tickets. Implementation of `getSessionTickets()` and `setSessionTickets()` is compatible with older versions of wolfSSL.
Adds macro `WOLFSSL_MAX_SESSION_TICKET_LEN` with default value 2048, which is used in `getSessionTickets()` to generate a byte array to copy the ticket to before generating a correctly sized jbyteArray.
Unit tests aim to check functionality of new functions and ability to resume TLS1.3 session with session tickets.
> JNI: Implement get/set session tickets
